import arcade

DESC = 'desc'
NORTH = 'north'
SOUTH = 'south'
EAST = 'east'
WEST = 'west'
UP = 'up'
DOWN = 'down'
GROUND = 'ground'
SHOP = 'shop'
GROUNDDESC = 'grounddesc'
SHORTDESC = 'shortdesc'
LONGDESC = 'longdesc'
TAKEABLE = 'takeable'
EDIBLE = 'edible'
DESCWORDS = 'descwords'
PRICE = 'price'
CREATURES = 'creatures'
TALKABLE = 'talkable'
GREETING = 'greeting'
HEALTH = 'health'
STRENGTH = 'strength'
DEFENCE = 'defence'
SPEED = 'speed'
GOLD = 'gold'
DRINKABLE = 'drinkable'
EQUIPABLE = 'equipable'
STATS = 'stats'
#AUTOATTACK = 'autoattack'
LOCKED = 'locked'
EXP = 'exp'
SAVE = 'save'
EQUIPTYPE = 'equiptype'
WILD = 'wild'
PERCEPTION = 'perception'
BOSS = 'boss'
COLOR = 'color'
QUESTITEM = 'questitem'
CUTSCENE = 'cutscene'
#MUSIC = 'music'
DROPITEM = 'dropitem'
MAXHEALTH = 'maxhealth'
SIDEQUEST = 'sidequest'
SIDEQUESTSTART = 'sidequeststart'
SIDEQUESTITEMS = 'sidequestitems'
SIDEQUESTEND = 'sidequestend'
SIDEQUESTREWARD = 'sidequestreward'
SIDEQUESTINV = 'sidequestinv'
DRAGON = 'dragon'
SHARK = 'shark'
SPRITE = 'sprite'

SCREEN_WIDTH = 80
WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

WINDOW_TITLE = "The Mystery of the Great Magical MacGuffin"
WINDOW_BACKGROUND_COLOR = arcade.color.WHITE

location = 'Your Bedroom' # starting location
inventory = []
equipped = ['Fancy Shoes', 'Cheap Hat', 'Favorite Trousers', 'Dirty Shirt']
showFullExits = True
stats = [15, 3, 3, 0, 5] #Health, Strength, Defence, Perception, Speed
level = 1
exp = 0
firstName = None
lastName = None
maxHealth = stats[0]
gold = 15
saveloc = 'Your Bedroom'
enemy = None
head = 0
chest = 0
hands = 0
legs = 0
feet = 0
yn = None
expeditionTimer = -1
expeditionLength = 0
maxHealthbar = 100
healthbar = (stats[0]/maxHealth)*maxHealthbar
displayCreature = 0
roomText = None
