from variables import *

"""
List of all items
"""

worldItems = {
    'Short Sword' : {
        GROUNDDESC: 'A short sword lays on the ground.',
        SHORTDESC: 'a short sword',
        LONGDESC: 'An old short sword, you\'ve had it for as long as you can remember.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 2,
        DEFENCE: 0,
        SPEED: 0,
        PERCEPTION: 0,
        PRICE: 5,
        DESCWORDS: ['sword', 'short sword']},
    'Great Sword' : {
        GROUNDDESC: 'A great sword lays on the ground.',
        SHORTDESC: 'a great sword',
        LONGDESC: 'The sword looks battle-worn, but ready to get some more.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 10,
        DEFENCE: 1,
        SPEED: -1,
        PERCEPTION: 0,
        PRICE: 15,
        DESCWORDS: ['sword', 'great sword']},
    'Dragonslayer Sword' : {
        GROUNDDESC: 'On a pedestal in the middle of the room lays the sword of the dragonslayer.',
        SHORTDESC: 'the sword of the dragonslayer',
        LONGDESC: 'This sword once belonged to your grandfather, who used it to slay dragons when he was young. it radiates energy from the blood it has spilled.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 12,
        DEFENCE: 2,
        SPEED: -1,
        PERCEPTION: 0,
        QUESTITEM: True,
        PRICE: 0,
        DESCWORDS: ['sword', 'dragonslayer sword', 'sword of the dragonslayer']},
    'Bow' : {
        GROUNDDESC: 'A bow lays on the ground, a lot of arrows in a quiver next to it.',
        SHORTDESC: 'a bow',
        LONGDESC: 'That\'s a lot of arrows.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 6,
        DEFENCE: 0,
        SPEED: 1,
        PERCEPTION: 3,
        PRICE: 20,
        DESCWORDS: ['bow']},
    'Crossbow' : {
        GROUNDDESC: 'A crossbow lays on the ground.',
        SHORTDESC: 'a crossbow',
        LONGDESC: 'It\'s not clear where the arrows come from, but it loads them automatically.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 10,
        DEFENCE: 0,
        SPEED: 0,
        PERCEPTION: 3,
        PRICE: 35,
        DESCWORDS: ['crossbow']},
    'Scoped Crossbow' : {
        GROUNDDESC: 'A scoped crossbow lays on the ground.',
        SHORTDESC: 'the scoped crossbow',
        LONGDESC: 'Someone has modified this crossbow, a scope has been added alongside some extra cogs and springs.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 12,
        DEFENCE: 0,
        SPEED: 0,
        PERCEPTION: 7,
        PRICE: 60,
        DESCWORDS: ['crossbow']},
    'Spear' : {
        GROUNDDESC: 'A spear lays on the ground.',
        SHORTDESC: 'the spear',
        LONGDESC: 'The spear has a sharp point and a sturdy handle, but you\'ll need great aim to hit someone where it hurts.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 12,
        DEFENCE: 0,
        SPEED: 1,
        PERCEPTION: -3,
        PRICE: 10,
        DESCWORDS: ['spear']},
    'Leather Chestplate' : {
        GROUNDDESC: 'A leather chestplate lays on the ground.',
        SHORTDESC: 'a leather chestplate',
        LONGDESC: 'A simple leather chestplate, nothing fancy but it gets the job done.',
        EQUIPABLE: True,
        EQUIPTYPE: 'CHEST',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 2,
        SPEED: 0,
        PERCEPTION: 0,
        PRICE: 7,
        DESCWORDS: ['chestplate', 'leather chestplate']},
    'Leather Trousers' : {
        GROUNDDESC: 'A pair of leather trousers lay on the ground.',
        SHORTDESC: 'leather trousers',
        LONGDESC: 'A simple pair of leather trousers, kind of impractical but sturdier than textile.',
        EQUIPABLE: True,
        EQUIPTYPE: 'CHEST',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 2,
        SPEED: 0,
        PERCEPTION: 0,
        PRICE: 7,
        DESCWORDS: ['chestplate', 'leather chestplate']},
    'Leather Boots' : {
        GROUNDDESC: 'A pair of leather boots lays on the ground.',
        SHORTDESC: 'the leather boots',
        LONGDESC: 'sturdy yet flexible, the dream of everyone that works out in the fields.',
        EQUIPABLE: True,
        EQUIPTYPE: 'FEET',
        STATS: True,
        STRENGTH: 1,
        DEFENCE: 2,
        SPEED: 1,
        PERCEPTION: 0,
        PRICE: 75,
        DESCWORDS: ['boots', 'leather boots']},    
    'Iron Chestplate' : {
        GROUNDDESC: 'An iron chestplate lays on the ground.',
        SHORTDESC: 'an iron chestplate',
        LONGDESC: 'An iron chestplate, it looks like it can take some heavy hits.',
        EQUIPABLE: True,
        EQUIPTYPE: 'CHEST',
        STATS: True,
        STRENGTH: 1,
        DEFENCE: 5,
        SPEED: -1,
        PERCEPTION: 0,
        PRICE: 20,
        DESCWORDS: ['chestplate', 'iron chestplate']},
    'Steel Chestplate' : {
        GROUNDDESC: 'A steel chestplate lays on the ground.',
        SHORTDESC: 'a steel chestplate',
        LONGDESC: 'A steel chestplate, to take the heaviest of hits.',
        EQUIPABLE: True,
        EQUIPTYPE: 'CHEST',
        STATS: True,
        STRENGTH: 2,
        DEFENCE: 10,
        SPEED: -3,
        PERCEPTION: 0,
        PRICE: 45,
        DESCWORDS: ['chestplate', 'steel chestplate']},
    'Molten Chestplate' : {
        GROUNDDESC: 'A molten chestplate lays on the ground.',
        SHORTDESC: 'a molten chestplate',
        LONGDESC: 'A chestplate composed of magma, enchanted to not hurt it\'s wearer',
        EQUIPABLE: True,
        EQUIPTYPE: 'CHEST',
        STATS: True,
        STRENGTH: 3,
        DEFENCE: 15,
        SPEED: -4,
        PERCEPTION: 0,
        PRICE: 100,
        DESCWORDS: ['chestplate', 'molten chestplate']},
    'Cheap Hat' : {
        GROUNDDESC: 'Your hat lays on the ground.',
        SHORTDESC: 'a hat',
        LONGDESC: 'This hat was kinda cheap, but it looks good',
        EQUIPABLE: True,
        EQUIPTYPE: 'HEAD',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 0,
        SPEED: 0,
        PERCEPTION: 1,
        PRICE: 5,
        DESCWORDS: ['hat', 'cheap hat']},
    'Dirty Shirt' : {
        GROUNDDESC: 'Your dirty shirt lays on the ground.',
        SHORTDESC: 'the dirty shirt',
        LONGDESC: 'You should really get to cleaning this shirt.',
        EQUIPABLE: True,
        EQUIPTYPE: 'CHEST',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 0,
        SPEED: 0,
        PERCEPTION: 0,
        PRICE: 5,
        DESCWORDS: ['shirt', 'dirty shirt']},
    'Favorite Trousers' : {
        GROUNDDESC: 'Your favorite trousers lay on the ground.',
        SHORTDESC: 'your favorite trousers',
        LONGDESC: 'These trousers are the best!',
        EQUIPABLE: True,
        EQUIPTYPE: 'LEGS',
        STATS: True,
        STRENGTH: 1,
        DEFENCE: 0,
        SPEED: 0,
        PERCEPTION: 0,
        PRICE: 15,
        DESCWORDS: ['trousers', 'pants', 'favorite trousers']},
    'Fancy Shoes' : {
        GROUNDDESC: 'Your fancy shoes lay on the ground.',
        SHORTDESC: 'the fancy shoes',
        LONGDESC: 'You paid good money for these shoes, but they wont offer much protection.',
        EQUIPABLE: True,
        EQUIPTYPE: 'FEET',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 0,
        SPEED: 1,
        PERCEPTION: 0,
        PRICE: 75,
        DESCWORDS: ['shoes', 'fancy shoes']},
    'Bed' : {
        GROUNDDESC: 'A single person bed is shoved against the wall.',
        SHORTDESC: 'a bed.',
        LONGDESC: 'A single person bed with a mattress filled with straw. It hasn\'t been cleaned in a while.',
        TAKEABLE: False,
        HEALTH: 20,
        MAXHEALTH: 20, 
        DESCWORDS: ['bed']},
    'Dresser' : {
        GROUNDDESC: 'A wooden dresser stands against the wall.',
        SHORTDESC: 'a dresser.',
        LONGDESC: 'A simple wooden dresser, that has been in your family for some generations, that holds some secrets.',
        TAKEABLE: False,
        HEALTH: 15,
        MAXHEALTH: 15, 
        DESCWORDS: ['dresser']},
    'Table' : {
        GROUNDDESC: 'A small wooden table stands in the middle of the room.',
        SHORTDESC: 'a table.',
        LONGDESC: 'A simple wooden table with a big stack of papers on top of it. Many are old quests that you\'ve completed in the past.',
        TAKEABLE: False,
        HEALTH: 10,
        MAXHEALTH: 10, 
        DESCWORDS: ['table']},
    'Chair' : {
        GROUNDDESC: 'A wooden chair with a missing leg, it\'s seen better days :(',
        SHORTDESC: 'A chair',
        LONGDESC: 'A chair',
        TAKEABLE: True,
        HEALTH: 5,
        MAXHEALTH: 5,
        DESCWORDS: ['chair']},
    'Old Table' : {
        GROUNDDESC: 'An old table with only some minor holes in the middle of it',
        SHORTDESC: 'An old table',
        TAKEABLE: True,
        HEALTH: 7,
        MAXHEALTH: 7,
        DESCWORDS: ['old table']},
    'Broken lamp' : {
        GROUNDDESC: 'A lamp with gaps all over the place, the bulb seems to still be working, it apears to be quite old and is covered in dust',
        SHORTDESC: 'Lamp',
        LONGDESC: 'Attracts Moths, might come in handy somewhere else.',
        TAKEABLE: True,
        HEALTH: 30,
        MAXHEALTH: 30,
        DESCWORDS: ['Lamp']},
    'Minor Health Potion' : {
        GROUNDDESC: 'A minor health potion lays on the ground.',
        SHORTDESC: 'a minor health potion',
        LONGDESC: 'A magical concoction that tops up your health points',
        DRINKABLE: True,
        HEALTH: 5,
        DESCWORDS: ['minor health potion', 'health potion', 'potion']},
    'Key' : {
        GROUNDDESC: 'A key lays on the ground.',
        SHORTDESC: 'a key',
        LONGDESC: 'A key.',
        DESCWORDS: ['key']},
    'Frog Leg' : {
        GROUNDDESC: 'A frog leg lays on the ground.',
        SHORTDESC: 'a frog leg',
        LONGDESC: 'A frog leg.',
        PRICE: 1,
        DESCWORDS: ['frog leg']},
    'Feathers' : {
        GROUNDDESC: 'Feathers lays on the ground.',
        SHORTDESC: 'feathers',
        LONGDESC: 'Feathers.',
        PRICE: 2,
        DESCWORDS: ['feathers']},
    'Cow Hide' : {
        GROUNDDESC: 'A cow hide lays on the ground.',
        SHORTDESC: 'a cow hide',
        LONGDESC: 'A cow hide.',
        PRICE: 3,
        DESCWORDS: ['cow hide']},
    'Wolf Fang' : {
        GROUNDDESC: 'A wolf fang lays on the ground.',
        SHORTDESC: 'a wolf fang',
        LONGDESC: 'A wolf fang.',
        PRICE: 5,
        DESCWORDS: ['wolf fang']},
    'Beast Egg' : {
        GROUNDDESC: 'A Beast Egg lays on the ground.',
        SHORTDESC: 'the beast egg',
        LONGDESC: 'It\'s a really big egg.',
        QUESTITEM: True,
        PRICE: 0,
        DESCWORDS: ['egg', 'big egg', 'monster egg', 'beast egg']},
    'Hidden Gem' : {
        GROUNDDESC: 'A hidden gem lays on the ground.',
        SHORTDESC: 'the hidden gem',
        LONGDESC: 'Forged beyond reach of the Mechanical Artists, this gem is still pure.',
        QUESTITEM: True,
        PRICE: 0,
        DESCWORDS: ['gem', 'hidden gem']},
    'Unicorn Hair' : {
        GROUNDDESC: 'Unicorn hair lays on the ground.',
        SHORTDESC: 'unicorn hair',
        LONGDESC: 'Unicorn hair.',
        PRICE: 50,
        DESCWORDS: ['unicorn hair', 'hair']},
    'Boring Book' : {
        GROUNDDESC: 'A boring book, reading it is not recommended',
        SHORTDESC: 'the boring book',
        LONGDESC: 'Dont even bother opening this book as its boredom will make you feel asleep instantaneously.',
        QUESTITEM: False,
        TAKEABLE: False,
        DESCWORDS: ['boring book']},
    'Book' : {
        GROUNDDESC: 'An interesting looking book is convieniently placed on a table in the middle of the room.',
        SHORTDESC: 'the book',
        LONGDESC: 'This book looks like you should really take it with you for some reason.',
        QUESTITEM: True,
        PRICE: 0,
        DESCWORDS: ['book']},
    'Huge Helmet' : {
        GROUNDDESC: 'An huge helmet is convieniently placed on a display in the middle of the room.',
        SHORTDESC: 'the huge helmet',
        LONGDESC: 'This helmet won\'t fit you, but you really want to take it.',
        QUESTITEM: True,
        PRICE: 0,
        DESCWORDS: ['huge helmet', 'helmet']},
    'Fried Lizard' : {
        GROUNDDESC: 'A fried Lizard lays on the ground.',
        SHORTDESC: 'a fried Lizard',
        LONGDESC: 'A local delicacy, made by burning fire lizards in their own heat',
        EDIBLE: True,
        STATS: True,
        HEALTH: 6,
        STRENGTH: 0,
        DEFENCE: 0,
        SPEED: 0,
        PERCEPTION: 0,
        DESCWORDS: ['fried lizard', 'lizard']},
    'Miner\'s Helmet' : {
        GROUNDDESC: 'A yellow helmet with a bright light at the front.',
        SHORTDESC: 'the miner\'s helmet',
        LONGDESC: 'The helmet has a massive battery on the left, that will be heavy to wear.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HEAD',
        STATS: True,
        STRENGTH: 1,
        DEFENCE: 6,
        SPEED: 0,
        PERCEPTION: 7,
        PRICE: 30,
        DESCWORDS: ['helmet', 'mine helmet', 'miner helmet', 'miners helmet', 'miner\'s helmet']},
    'True Surviver Helmet' : {
        GROUNDDESC: 'A camo print helmet with weird looking goggles lays on the ground.',
        SHORTDESC: 'the true surviver helmet',
        LONGDESC: 'The sturdy helmet has a pair of large goggles with both infra-red and nightvision modes.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HEAD',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 3,
        SPEED: 0,
        PERCEPTION: 7,
        PRICE: 25,
        DESCWORDS: ['helmet', 'surviver helmet', 'true surviver helmet']},
    'True Surviver Chestplate' : {
        GROUNDDESC: 'A thin, camo print chestplate lays on the ground.',
        SHORTDESC: 'the true surviver chestplate',
        LONGDESC: 'The chestplate is surprisingly heavy compared to its thickness. Although it\'s still light enough to creep around the woods.',
        EQUIPABLE: True,
        EQUIPTYPE: 'CHEST',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 10,
        SPEED: 0,
        PERCEPTION: 0,
        PRICE: 50,
        DESCWORDS: ['chestplate', 'surviver chestplate', 'true surviver chestplate']},
    'True Surviver Trousers' : {
        GROUNDDESC: 'A pair of camo print trousers lay on the ground.',
        SHORTDESC: 'the true surviver trousers',
        LONGDESC: 'The trousers are so light, you feel like you could run 50 miles in them and still not get tired.',
        EQUIPABLE: True,
        EQUIPTYPE: 'LEGS',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 5,
        SPEED: 5,
        PERCEPTION: 0,
        PRICE: 30,
        DESCWORDS: ['trousers', 'surviver trousers', 'true surviver trousers']},
    'True Surviver Boots' : {
        GROUNDDESC: 'A pair of camo print boots lay on the ground.',
        SHORTDESC: 'the true surviver boots',
        LONGDESC: 'The boots look like strong and with the steel noses you could probably do some damage.',
        EQUIPABLE: True,
        EQUIPTYPE: 'FEET',
        STATS: True,
        STRENGTH: 2,
        DEFENCE: 3,
        SPEED: 5,
        PERCEPTION: 0,
        PRICE: 25,
        DESCWORDS: ['boots', 'surviver boots', 'true surviver boots']},
    'Shark Tooth' : {
        GROUNDDESC: 'A tooth from the underwater beast that you have defeated, effective especially to its own species...',
        SHORTDESC: 'A sharktooth',
        LONGDESC: 'Not one of the big teeth he had upfront, easily three times the size of you, this one was a bit in the back and fell out when you killed the beast',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 8,
        DEFENCE: 2,
        SPEED: 3,
        PERCEPTION: 0,
        PRICE: 0,
        DESCWORDS: ['shark tooth', 'brucy\'s tooth']},
    'Poseidon\'s Trident' : {
        GROUNDDESC: 'The long lost Trident of the old ruler of the sea, Poseidon, nobody knows why it has 3 spearpoints, but it just does and you are going to have to deal with it.',
        SHORTDESC: 'Poseidon\'s Trident',
        LONGDESC: 'A trident ready to murder any creatures you encounter under water',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 8,
        DEFENCE: 3,
        SPEED: 5,
        PERCEPTION: 1,
        PRICE: 0,
        DESCWORDS: ['trident', 'poseidon\'s trident']},
    'Sunken Ship Wreck' : {
        GROUNDDESC: 'The remains of a ship that sunk months, maybe years ago. All that is left is a basic ship shape filled with cracks and holes, and somehow the ship mast stayed intact too...',
        SHORTDESC: 'A Ship Wreck',
        LONGDESC: 'Remains of a sunken ship',
        TAKEABLE: False,
        HEALTH: 5,
        MAXHEALTH: 5,
        DESCWORDS: ['ship wreck', 'wreck']},
    'Sea Anemone' : {
        GROUNDDESC: 'A Coral, home to fish and a producer of food for even more fish, and while it is doing all that it still managed to look pretty as well.',
        SHORTDESC: 'A Sea Anemone',
        LONGDESC: 'A Sea Anemone, a pretty piece of the coral reef',
        TAKEABLE: False,
        HEALTH: 5,
        MAXHEALTH: 5,
        DESCWORDS: ['sea anemone', 'anemone']},
    'Sea Broccoli' : {
        GROUNDDESC: 'A Majestic Sea Broccoli, ready to be eaten, might cause side effects...',
        SHORTDESC: 'A Sea Broccoli.',
        LONGDESC: 'A Sea Broccoli that will heal your wounds',
        EDIBLE: True,
        HEALTH: 7,
        DESCWORDS: ['sea broccoli']},
    'Felwinter\'s lie' : {
        GROUNDDESC: 'Next to the skeleton lays a majestic dagger. The handle is woven with purple leather, golden ornaments are placed along side the hilt.',
        SHORTDESC: 'Felwinter\'s lie',
        LONGDESC: 'Presumably the weapon of Felwinter. A name which did not survive the passage of time.',
        EQUIPABLE: True,
        EQUIPTYPE: 'HANDS',
        STATS: True,
        STRENGTH: 12,
        DEFENCE: 0,
        SPEED: 9,
        PERCEPTION: 4,
        PRICE: 0,
        DESCWORDS: ['dagger']},
    'Jersey' : {
        GROUNDDESC: 'A football jersey of your favorite soccerteam.',
        SHORTDESC: 'Jersey',
        LONGDESC: 'A tight fitting jersey of FC Emmen',
        EQUIPABLE: True,
        EQUIPTYPE: 'BODY',
        STATS: True,
        STRENGTH: 0,
        DEFENCE: 300,
        SPEED: 13,
        PERCEPTION: 1,
        PRICE: 50000,
        DESCWORDS: ['jersey']},
}