from variables import *

"""
List of all locations
"""

worldRooms = {
    'Your Bedroom' : {
        COLOR: 'YELLOW',
        SPRITE: 'inside',
        DESC: 'Your bedroom is a small, but comfortable room with only a bed and a dresser. There\'s a trapdoor on the ground.',
        DOWN: 'Your Livingroom',
        SAVE: True,
        CREATURES: [],
        SHOP: [],
        GROUND: ['Leather Chestplate']},
    'Your Livingroom' : {
        COLOR: 'YELLOW',
        SPRITE: 'inside',
        DESC: 'Your livingroom is a bit cramped, but large enough for a single person. There\'s a door to the south',
        UP: 'Your Bedroom',
        SOUTH: 'Black Alley',
        CREATURES: ['Dummy'],
        GROUND: ['Short Sword', 'Minor Health Potion',]},
    'Black Alley' : {
        CUTSCENE: True,
        COLOR: 'BLUE',
        SPRITE: 'street',
        DESC: 'A small alley named "Black Alley" because it\'s always pitch black in the alley no matter what time of day it is.',
        NORTH: 'Your Livingroom',
        EAST: 'Lower Maroon Street',
        DOWN: 'Sewer',
        CREATURES: ['Depressed Pig'],
        GROUND: []},
    'Sewer Entrance' : {
        COLOR: 'GREEN',
        SPRITE:'street',
        DESC: 'The sewersystem spreads all around the city.',
        UP: 'Black Alley',
        DOWN: 'Sewer: level 1B',
        LOCKED: True,
        CREATURES: [],
        GROUND: []},
    'Sewer:level 1A' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        NORTH:'Sewer:level 1C',
        EAST:'Sewer:level 1B',
        CREATURES: [],
        GROUND: []},
    'Sewer:level 1B' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        UP: 'Sewer Entrance',
        NORTH:'Sewer:level 1D',
        WEST:'Sewer:level 1A',
        CREATURES: [],
        GROUND: []},
    'Sewer:level 1C' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        EAST:'Sewer:level 1D',
        SOUTH:'Sewer:level 1A',
        DOWN:'Sewer:level 2A',
        CREATURES: ['Mutated Rat'],
        GROUND: []},
    'Sewer:level 1D' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        SOUTH:'Sewer:level 1B',
        WEST:'Sewer:level 1C',
        CREATURES: [],
        GROUND: []},
    #-------------
     'Sewer:level 2A' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        NORTH:'Sewer:level 2C',
        UP: 'Sewer:level 1C',
        EAST:'Sewer:level 2B',
        CREATURES: [],
        GROUND: []},
    'Sewer:level 2B' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        NORTH:'Sewer:level 2D',
        WEST:'Sewer:level 2A',
        CREATURES: [],
        GROUND: []},
    'Sewer:level 2C' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        EAST:'Sewer:level 2D',
        SOUTH:'Sewer:level 2A',
        CREATURES: ['Mutated Rat'],
        GROUND: []},
    'Sewer:level 2D' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        SOUTH:'Sewer:level 1B',
        DOWN:'Sewer:level 3D',
        WEST:'Sewer:level 1C',
        CREATURES: [],
        GROUND: []},
    #-----------------3
    'Sewer:level 3A' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        NORTH:'Sewer:level 3C',
        EAST:'Sewer:level 3B',
        CREATURES: [],
        GROUND: []},
    'Sewer:level 3B' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        NORTH:'Sewer:level 3D',
        WEST:'Sewer:level 3A',
        DOWN:'Sewer:level 4D',
        CREATURES: ['Mutated Rat', 'Statue'],
        GROUND: []},
    'Sewer:level 3C' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        EAST:'Sewer:level 3D',
        SOUTH:'Sewer:level 3A',
        CREATURES: [],
        GROUND: []},
    'Sewer:level 3D' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The sewersystem spreads all around the city.',
        SOUTH:'Sewer:level 3B',
        WEST:'Sewer:level 3C',
        UP: 'Sewer:level 2D',
        CREATURES: ['Statue'],
        GROUND: []},
#--------------------
    'Sewer:level 4D' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'You never knew the sewers went so deep.',
        UP:'Sewer:level 3B',
        NORTH:'Sewer Stairs',
        CREATURES: ['Statue'],
        GROUND: []},
    'Sewer Stairs' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The room beneath gives off a dreadfull aura. Everything says you should not continue this path.',
        SOUTH:'Sewer:lever 4D',
        NORTH:'Chamber of warnings',
        CREATURES: ['Statue','Statue'],
        GROUND: []},
    'Chamber of warnings' : {
        COLOR: 'GREEN',
        SPRITE:'sewer',
        DESC: 'The room beneath gives off a dreadfull aura. Everything says you should not continue this path.',
        SOUTH:'Sewer Stairs',
        NORTH:'DO NOT ENTER',
        CREATURES: ['Statue','Statue','Statue'],
        GROUND: []},
    'DO NOT ENTER' : {
        COLOR: 'GREEN',
        CUTSCENE: True,
        SPRITE:'sewer',
        DESC: 'The room beneath gives off a dreadfull aura. Everything says you should not continue this path.',
        CREATURES: [''],
        GROUND: []},
    'Prism Square Ruined' : {
        COLOR: 'GREEN',
        SPRITE:'prism square grey',
        DESC: 'The Prism Square you once knew is now ruined. Everything you were familiar with in this place is now in the past. Everything because of him, Ta\'xeq.',
        CREATURES: ['Ta\'xeq, Spawn of Death'],
        GROUND: []},
    'Lower Maroon Street' : {
        COLOR: 'RED',
        SPRITE:'street',
        DESC: 'One of the larger streets in Otolo.',
        NORTH: 'Middle Maroon Street',
        EAST: 'The Grey Horse Tavern',
        SOUTH: 'Town Exit South',
        WEST: 'Black Alley',
        CREATURES: [],
        GROUND: []},
    'Middle Maroon Street' : {
        COLOR: 'RED',
        SPRITE:'street',
        DESC: 'One of the larger streets in Otolo.',
        NORTH: 'Upper Maroon Street',
        SOUTH: 'Lower Maroon Street',
        WEST: 'Black Alley',
        CREATURES: [],
        GROUND: []},
    'Upper Maroon Street' : {
        COLOR: 'RED',
        SPRITE:'street',
        DESC: 'One of the larger streets in Otolo.',
        NORTH: 'Prism Square',
        SOUTH: 'Middle Maroon Street',
        EAST: 'Ingrid\'s Inn', 
        WEST: 'Egar\'s Swords and Other Sharp Objects',
        CREATURES: [],
        GROUND: []},
    'Ingrid\'s Inn' : {
        SPRITE: 'inside',
        DESC: 'A cozy and popular inn.',
        UP: 'Room4Rent',
        WEST: 'Upper Maroon Street',
        CREATURES: [],
        GROUND: []},
    'Room4Rent' : {
        SPRITE: 'inside',
        DESC: 'A tiny room with a bed.',
        DOWN: 'Ingrid\'s Inn',
        SAVE: True,
        CREATURES: [],
        GROUND: []},
    'Prism Square' : {
        DESC: 'The middle point of Otolo, the Prism Square.',
        NORTH: 'Tower Entry',
        SPRITE:'prism square',
        EAST: 'Upper Ochreous Road',
        SOUTH: 'Upper Maroon Street',
        WEST: 'Upper Aqua Avenue',
        CREATURES: [],
        GROUND: []},
    'Tower Entry' : {
        COLOR: 'GRAY',
        SPRITE:'tower white',
        DESC: 'The room has a high ceiling with light seemingly coming in from all sides. There\'s a large staircase in the middel of the room, leading straight into a wall.',
        NORTH: 'Large Stairs',
        SOUTH: 'Prism Square',
        CREATURES: [],
        GROUND: []},
    'Large Stairs' : {
        CUTSCENE: True,
        SPRITE:'tower white',
        DESC: 'Large Stairs lead straight into a wall. ',
        CREATURES: [],
        GROUND: []},
    'Red Floor Save Room' : {
        SAVE: True,
        COLOR: 'RED',
        SPRITE:'tower red',
        DESC: 'A small fire is burning in the middle of the room. In front of you is a dark hallway that doesn\'t seem to have an end.',
        NORTH: 'Red Northern Hallway Entry',
        CREATURES: [],
        GROUND: []},
    'Red Northern Hallway Entry' : {
        COLOR: 'RED',
        SPRITE:'tower red',
        DESC: 'The hallway is dimly lit by torches that a mounted to the wall. ',
        NORTH: 'Red Northern Hallway Middle',
        SOUTH: 'Red Floor Save Room',
        CREATURES: ['Fire Spirit','Fire Spirit'],
        GROUND: []},
    'Red Northern Hallway Middle' : {
        COLOR: 'RED',
        SPRITE:'tower red',
        DESC: '',
        NORTH: 'Red Northern Hallway End',
        SOUTH: 'Red Northern Hallway Entry',
        CREATURES: ['Fire Spirit','Fire Spirit','Small Fire Spirit'],
        GROUND: []},
    'Red Northern Hallway End' : {
        COLOR: 'RED',
        SPRITE:'tower red',
        DESC: 'The part of hallway feels a lot warmer. ',
        NORTH: 'Red Corner',
        SOUTH: 'Red Northern Hallway Middle',
        CREATURES: ['Small Fire Spirit', 'Small Fire Spirit','Fire Spirit'],
        GROUND: []},
    'Red Corner' : {
        COLOR: 'RED',
        SPRITE:'tower red',
        DESC: 'A large, bright fire stands in the middle of the room',
        EAST: 'Red Eastern Hallway Entry',
        SOUTH: 'Red Northern Hallway End',
        CREATURES: ['Large Fire Spirit'],
        GROUND: []},
    'Red Eastern Hallway Entry' : {
        COLOR: 'RED',
        SPRITE:'tower red',
        DESC: 'You can feel the fire burning from the room you have just left.',
        EAST:'Red Eastern Hallway Middle' ,
        WEST:'' ,
        CREATURES: ['Fire Spirit','Fire Spirit','Fire Spirit','Fire Spirit','Fire Spirit'],
        GROUND: []},
    'Red Eastern Hallway Middle' : {
        COLOR: 'RED',
        SPRITE:'tower red',
        DESC: 'The warmth behind subdues, however you feel a new source of heat comming from upfront.',
        EAST:'Red Eastern Hallway End' ,
        WEST:'Red Eastern Hallway Entry' ,
        CREATURES: ['Large Fire Spirit','Small Fire Spirit','Small Fire Spirit'],
        GROUND: []},
    'Red Eastern Hallway End' : {
        COLOR: 'RED',
        SPRITE:'tower red',
        DESC: 'You should have brought some water with you, dehydration is becoming an issue with all this heat',
        EAST: 'Brown Stairs' ,
        WEST: 'Red Eastern Hallway Middle',
        CREATURES: ['Large Fire Spirit','Large Fire Spirit'],
        GROUND: []},
    'Brown Stairs' : {
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'You have already faced golems before, but this one is different. It feels as if the sun resides within in this room.',
        UP:'Brown Floor Save Room' ,
        WEST:'Red Eastern Hallway End',
        CREATURES: ['Cyronax, Spawn of Ash'],
        GROUND: []},
    'Brown Floor Save Room' : {
        SAVE: True, #welke kleuren zijn er?
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'A small fire is burning in the middle of the room. In front of you is a dark hallway that doesn\'t seem to have an end.',
        SOUTH: 'Brown Northern Hallway Entry',
        CREATURES: [''],
        GROUND: ['Minor Health Potion']},
    'Brown Southern Hallway Entry' : {
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'You find yourself in another hallway. Flowers grow on the ground and walls, some of which give light. ',
        SOUTH: 'Brown Southern Hallway Middle',
        NORTH: 'Brown Floor Save Room',
        CREATURES: ['Earth Spirit'],
        GROUND: []},
    'Brown Southern Hallway Middle' : {
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'Flowers grow on the ground and walls, some of which give light',
        SOUTH: 'Brown Southern Hallway End',
        NORTH: 'Brown Southern Hallway Entry',
        CREATURES: ['Earth Spirit','Small Earth Spirit','Earth Spirit'],
        GROUND: []},
    'Brown Southern Hallway End' : {
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'Flowers grow on the ground and walls, some of which give light. Another source of light resides upfront, one which shines brighter than the rest.',
        SOUTH: 'Brown Corner',
        NORTH: 'Brown Southern Hallway Middle',
        CREATURES: ['Small Earth Spirit', 'Small Earth Spirit', 'Small Earth Spirit'],
        GROUND: []},
    'Brown Corner' : {
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'A tree grows in the middle of this space, the fruits of this tree shines bright',
        WEST: 'Brown Western Hallway Entry',
        NORTH: 'Brown Southern Hallway End',
        CREATURES: ['Large Earth Spirit', 'Earth Spirit'],
        GROUND: []},
    'Brown Western Hallway Entry' : {
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'Flowers grow on the ground and walls, some of which give light.',
        WEST: 'Brown Western Hallway Middle',
        EAST: 'Brown Corner',
        CREATURES: ['Large Earth Spirit', 'Small Earth Spirit'],
        GROUND: []},
    'Brown Western Hallway Middle' : {
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'Flowers grow on the ground and walls, some of which give light.',
        WEST: 'Brown Western Hallway End',
        EAST: 'Brown Western Hallway Entry',
        CREATURES: ['Large Earth Spirit, Small Earth Spirit','Earth Spirit'],
        GROUND: []},
    'Brown Western Hallway End' : {
        COLOR: 'RED',
        SPRITE:'tower brown',
        DESC: 'Flowers grow on the ground and walls, some of which give light.',
        WEST: 'Blue Stairs',
        EAST: 'Brown Western Hallway Middle',
        CREATURES: ['Large Earth Spirit, Small Earth Spirit','Large Earth Spirit'],
        GROUND: []},
    'Blue Stairs' : {
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'You can hear water flowing from above The majesticy crafted stairts are guarded by a golem, this one bigger than before.',
        UP: 'Blue Floor Save Room',
        EAST: 'Brown Western Hallway End',
        CREATURES: ['Chelchis, Kell of Stone'],
        GROUND: []},
    'Blue Floor Save Room' : {
        SAVE: True, #welke kleuren zijn er?
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'A small fire is burning in the middle of the room. In front of you is a dark hallway that doesn\'t seem to have an end.',
        SOUTH: 'Brown Northern Hallway Entry',
        CREATURES: [''],
        GROUND: ['Minor Health Potion']},
    'Blue Northern Hallway Entry' : {
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'Upon entering the hallway you find yourself standing infront of a raft. The water it floats on has a stunning blue color, yet it has something omnimous to it.',
        NORTH: 'Blue Northern Hallway Middle',
        SOUTH: 'Blue Floor Save Room',
        CREATURES: ['Water Spirit','Water Spirit','Water Spirit'],
        GROUND: []},
    'Blue Northern Hallway Middle' : {
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'The architecture of this tower is quite interesting. Magic makes a lot of things possible.',
        NORTH: 'Blue Northern Hallway End',
        SOUTH: 'Blue Northern Hallway Entry',
        CREATURES: ['Water Spirit','Small Water Spirit','Water Spirit'],
        GROUND: []},
    'Blue Northern Hallway End' : {
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'Land is spotted up ahead.',
        NORTH: 'Blue Corner',
        SOUTH: 'Blue Northern Hallway Middle',
        CREATURES: ['Water Spirit','Small Water Spirit','Small Water Spirit'],
        GROUND: []},
    'Blue Corner' : {
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'Land is spotted up ahead.',
        EAST: 'Blue Eastern Hallway Entry',
        SOUTH: 'Blue Northern Hallway End',
        CREATURES: ['Water Spirit','Large Water Spirit'],
        GROUND: []},
    'Blue Eastern Hallway Entry' : {
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'Land is spotted up ahead.',
        EAST: 'Blue Eastern Middle',
        WEST: 'Blue Eastern Corner',
        CREATURES: ['Small Water Spirit','Small Water Spirit','Small Water Spirit'],
        GROUND: []},
    'Blue Eastern Hallway Middle' : {
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'Land is spotted up ahead.',
        EAST: 'Blue Eastern Hallway End',
        WEST: 'Blue Eastern Hallway Entry',
        CREATURES: ['Large Water Spirit','Large Water Spirit','Water Spirit'],
        GROUND: []},
    'Blue Eastern Hallway End' : {
        COLOR: 'RED',
        SPRITE:'tower blue',
        DESC: 'Land is spotted up ahead.',
        EAST: 'White Stairs',
        WEST: 'Blue Eastern Hallway Middle',
        CREATURES: ['Large Water Spirit','Large Water Spirit'],
        GROUND: []},
    'White Stairs' : {
        COLOR: 'RED',
        SPRITE:'tower white',
        DESC: 'You drift into a huge lake. A small -what appears to be a- water golem resides in the middle of the lage. Behind it stairs float magically.',
        UP: 'White Floor Save Room',
        SOUTH: 'Blue Eastern Hallway End',
        CREATURES: ['Callisto Gan'],
        GROUND: []},
    'White Floor Save Room' : {
        SAVE: True, #welke kleuren zijn er?
        COLOR: 'RED',
        SPRITE:'tower white',
        DESC: 'A small fire is burning in the middle of the room. In front of you is a dark hallway that doesn\'t seem to have an end.',
        NORTH: 'Golden stairs',
        CREATURES: [''],
        GROUND: ['True Surviver Trousers','True Surviver Boots']},
    'Golden Stairs' : {
        COLOR: 'RED',
        SPRITE:'tower white',
        CUTSCENE: True, 
        DESC: 'The fog is being blown away by huge wind forces upfront.',
        EAST: 'White Western Hallway End',
        UP: 'Roof of the Tower',
        CREATURES: [''],
        GROUND: []},        
    'Roof of the Tower' : {
        COLOR: 'RED',
        SPRITE:'clouds',
        DESC: 'The scenery is outstanding, you never thought this village was so magnificent.',
        DOWN: 'Golden Stairs',
        NORTH: 'Portal',
        CREATURES: ['Aeres, the Northern Windcaller'],
        GROUND: []}, 
    'Portal' : {
        COLOR: 'RED',
        SPRITE:'prism square',
        DESC: '',
        SOUTH: 'Roof of the Tower',
        NORTH: 'Prism Square',
        CREATURES: [''],
        GROUND: []}, 
    'Upper Ochreous Road' : {
        COLOR: 'YELLOW',
        SPRITE: 'street',
        DESC: 'A rough road.',
        NORTH: 'St. Ruben Station',
        WEST: 'Prism Square',
        EAST: 'Middle Ochreous Road',
        CREATURES: [],
        GROUND: []},
    'St. Ruben Station' : {
        SPRITE: 'street',
        DESC: 'The central station of Ottolo, trains coming in and out all day long, there doesnt seem to be much passengers today though.',
        SOUTH: 'Upper Ochreous Road',
        EAST: 'Fred\'s Bread',
        CREATURES: [],
        GROUND: ['']},
    'Middle Ochreous Road' : {
        COLOR: 'YELLOW',
        SPRITE: 'street',
        DESC: 'A rough road.',
        NORTH: 'Fred\'s Bread',
        EAST: 'Lower Ochreous Road',
        WEST: 'Upper Ochreous Road',
        SOUTH: 'Madam Madame\'s Crazy Concoctions',
        CREATURES: [],
        GROUND: []},
    'Fred\'s Bread' : {
        SPRITE: 'inside',
        DESC: 'You could sence the gorgeous smell of fresh baked bread from a mile away. Fred\'s Bread welcomes you to their bakery.',
        SOUTH: 'Middle Ochreous Road',
        WEST: 'St. Ruben Station',
        CREATURES: [],
        GROUND: []},
    'Patty\'s Furniture' : {
        SPRITE: 'inside',
        DESC: 'Old Patty tryna sell you her antique tables and chairs, and her other, little less antique, junk',
        NORTH: 'Lower Aqua Avenue',
        CREATURES: ['Old Patty'],
        GROUND: ['Old Table', 'Chair', 'Lamp']},
    'Lower Ochreous Road' : {
        COLOR: 'YELLOW',
        SPRITE: 'street',
        DESC: 'A rough road.',
        EAST: 'Town Exit East',
        WEST: 'Middle Ochreous Road',
        SOUTH: 'Abandoned House',
        CREATURES: [],
        GROUND: []},
    'Abandoned House' : {
        COLOR: 'BEIGE',
        SPRITE: 'inside',
        DESC: 'An old house, mainly wooden, walls are filled with cracks and holes, you will have to watch your step as each step could be the one causing the entire thing to collapse.',
        NORTH: 'Lower Ochreous Road',
        UP: 'Attic',
        CREATURES: [],
        GROUND: []},
    'Attic' : {
        COLOR: 'BEIGE',
        SPRITE: 'street',
        DESC: 'The floor you are on is being held up by 2 single, old and eaten wooden pillars and there are only a couple of planks to walk on. Oh... There is also a wild motman',
        DOWN: 'Abandoned House',
        CREATURES: ['Wild Motman'],
        GROUND: []},
    'Upper Aqua Avenue' : {
        COLOR: 'BLUE',
        SPRITE: 'street',
        DESC: 'The sea is visible over the dunes',
        EAST: 'Prism Square',
        WEST: 'Middle Aqua Avenue', 
        NORTH: 'Library',
        CREATURES: [],
        GROUND: []},
    'Middle Aqua Avenue' : {
        COLOR: 'BLUE',
        SPRITE: 'street',
        DESC: 'The sea is visible over the dunes',
        EAST: 'Upper Aqua Avenue',
        NORTH: 'Derick\'s Dwarven Defence',
        WEST: 'Lower Aqua Avenue', 
        CREATURES: [],
        GROUND: []},
    'Library' : {
        COLOR: 'BROWN',
        SPRITE: 'inside',
        DESC: 'The local library, it has a lot of books and improves your Science gain.',
        SOUTH: 'Upper Aqua Avenue',
        GROUND: ['Boring Book']},
    'Lower Aqua Avenue' : {
        COLOR: 'BLUE',
        SPRITE: 'street',
        DESC: 'The sea is visible over the dunes',
        EAST: 'Middle Aqua Avenue', 
        WEST: 'Beach',
        SOUTH: 'Patty\'s Furniture',
        CREATURES: [],
        GROUND: []},
    'Egar\'s Swords and Other Sharp Objects' : {
        SPRITE: 'inside',
        DESC: 'A small shop where you can buy most weapons anyone could want. The walls are lined with weapons and behind the counter is a large Orc know as Egar.',
        EAST: 'Upper Maroon Street',
        SHOP: ['Short Sword', 'Great Sword', 'Bow', 'Crossbow', 'Spear'],
        CREATURES: ['Egar'],
        GROUND: []},
    'Derick\'s Dwarven Defence' : {
        SPRITE: 'inside',
        DESC: 'A hole in the wall where you can get the strongest armor. Working the forge is a stout Dwarf.',
        SOUTH: 'Middle Aqua Avenue',
        SHOP: ['Leather Chestplate', 'Iron Chestplate', 'Steel Chestplate'],
        CREATURES: ['Derick'],
        GROUND: []},
    'Madam Madame\'s Crazy Concoctions' : {
        SPRITE: 'inside',
        DESC: 'A dark alchemy lab filled with potions and cauldrons. On top of a stool in the middle of the room sits an ageless Elven Witch.',
        NORTH: 'Middle Ochreous Road',
        SHOP: ['Minor Health Potion'],
        CREATURES: ['Madam Madame'],
        GROUND: []},
    'The Grey Horse Tavern' : {
        SPRITE: 'inside',
        DESC: 'A crowded bar filled with the most wretched hive of scum and villainy. There\'s a Centaur behind the bar.',
        UP: 'Nate\'s Room',
        WEST: 'Lower Maroon Street',
        SHOP: [],
        CREATURES: ['Gray Horse'],
        GROUND: []},
    'Beach' : {
        COLOR: 'YELLOW',
        SPRITE: 'beach',
        DESC: 'The beach.',
        NORTH: 'Midori Forest',
        EAST: 'Lower Aqua Avenue',
        SOUTH: 'Midori Forest',
        WEST: 'Shore',
        CREATURES: [],
        GROUND: []},
    'Town Exit South' : {
        COLOR: 'RED',
        SPRITE: 'street',
        DESC: 'The edge of town.',
        NORTH: 'Lower Maroon Street',
        EAST: 'Midori Forest',
        SOUTH: 'Foot of Mt. Falco',
        WEST: 'Midori Forest',
        CREATURES: [],
        GROUND: []},
    'Town Exit East' : {
        COLOR: 'YELLOW',
        SPRITE: 'street',
        DESC: 'The edge of town.',
        NORTH: 'Midori Forest',
        EAST: 'Cave Entrance',
        SOUTH: 'Midori Forest',
        WEST: 'Lower Ochreous Road',
        CREATURES: [],
        GROUND: []},
    'Midori Forest' : {
        CUTSCENE: True,
        COLOR: 'GREEN',
        SPRITE: 'forest',
        WILD: True,
        DESC: 'There is forest all around.',
        NORTH: 'Midori Forest',
        EAST: 'Midori Forest',
        SOUTH: 'Midori Forest',
        WEST: 'Midori Forest',
        CREATURES: [],
        GROUND: []},
    'Urila\'s Survivers Corner' : {
        SPRITE: 'inside',
        DESC: 'A small cart pulled by ponies stands still in a clearing.',
        EAST: 'Town Exit East',
        SOUTH: 'Town Exit South',
        WEST: 'Beach',
        CREATURES: ['Urila'],
        GROUND: []},
    'Foot of Mt. Falco' : {
        COLOR: 'RED',
        SPRITE: 'volcano',
        DESC: 'The foot of a large volcano located to the south of Otolo.',
        SOUTH: 'Mt. Falco',
        NORTH: 'Town Exit South',
        CREATURES: [],
        #CREATURES: ['Gaea, of a Thousand Grounds'],
        GROUND: []},
    'Mt. Falco' : {
        CUTSCENE: True,
        COLOR: 'RED',
        SPRITE: 'volcano',
        DESC: 'Mount Falco has made the soil around Otolo very fertile, but also poses a serious risk whenever it erupts. You can only stand here safe because you solidified the lava.',
        EAST: 'Crater of Mt. Falco',
        NORTH: 'Foot of Mt. Falco',
        CREATURES: ['Lounge of Fire Lizards'],
        GROUND: []},
    'Crater of Mt. Falco' : {
        COLOR: 'RED',
        SPRITE: 'volcano',
        DESC: 'The crater of Mount Falco is filled with boiling lava, but there is a hole in the middle that can be reached by a small path.',
        EAST: 'Middle of the Crater of Mt. Falco',
        WEST: 'Mt. Falco',
        CREATURES: ['Lounge of Fire Lizards', 'Lava Snail'],
        GROUND: []},
    'Middle of the Crater of Mt. Falco' : {
        COLOR: 'RED',
        SPRITE: 'volcano',
        DESC: 'There is lava all around. there is a mysterious hole in the ground, too dark to see the bottom. If you jump down the hole, you wont be able to climb back up.',
        WEST: 'Crater of Mt. Falco',
        DOWN: 'Mysterious hole',
        CREATURES: ['Lava Snail'],
        GROUND: []},
    'Mysterious hole' : {
        SPRITE: 'cave',
        CUTSCENE: True,
        COLOR: 'RED',
        DESC: '',
        CREATURES: [],
        GROUND: []},
    'Entrance to the Temple of Fire' : {
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'The hole above you is just out of reach. A door in front of you is the only way to go.',
        NORTH: 'Main Hall of the Temple of Fire',
        CREATURES: ['Guardian of the Temple of Fire'],
        GROUND: []},
    'Main Hall of the Temple of Fire' : {
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'A massive hall with doors in every direction, lit by hundreds of flames.',
        SOUTH: 'Entrance to the Temple of Fire',
        EAST: 'Lower East Wing of the Temple of Fire',
        WEST: 'Lower West Wing of the Temple of Fire',
        NORTH: 'Shrine of the Temple of Fire',
        CREATURES: ['First Guardian of the Temple of Fire', 'Second Guardian of the Temple of Fire'],
        GROUND: []},
    'Shrine of the Temple of Fire' : {
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'A room with a shrine in the middle, holding a melting core that starts glowing as you walk in.',
        SOUTH: 'Main Hall of the Temple of Fire',
        CREATURES: [],
        GROUND: ['Molten Chestplate']},
    'Lower East Wing of the Temple of Fire' : {
        CUTSCENE: True,
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'A Passage filled to the brim with burning books, one of the doors is closed.',
        NORTH: 'Middle East Wing of the Temple of Fire',
        CREATURES: ['Mage of the Temple of Fire'],
        GROUND: []},
    'Middle East Wing of the Temple of Fire' : {
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'A library full of books.',
        NORTH: 'Upper East Wing of the Temple of Fire',
        SOUTH: 'Lower East Wing of the Temple of Fire',
        CREATURES: ['First Mage of the Temple of Fire', 'Second Mage of the Temple of Fire'],
        GROUND: ['Book']},
    'Upper East Wing of the Temple of Fire' : {
        CUTSCENE: True,
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'Even more books.',
        NORTH: 'Chamber of Ignisius',
        SOUTH: 'Middle East Wing of the Temple of Fire',
        CREATURES: ['Archmage of the Temple of Fire'],
        GROUND: []},
    'Lower West Wing of the Temple of Fire' : {
        CUTSCENE: True,
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'A Passage Full of freshly forged weaponry.',
        NORTH: 'Middle West Wing of the Temple of Fire',
        CREATURES: ['Guardian of the Temple of Fire'],
        GROUND: []},
    'Middle West Wing of the Temple of Fire' : {
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'An armory full of forges, anvils, weapons and armor.',
        NORTH: 'Upper West Wing of the Temple of Fire',
        SOUTH: 'Lower West Wing of the Temple of Fire',
        CREATURES: ['First Guardian of the Temple of Fire', 'Second Guardian of the Temple of Fire'],
        GROUND: ['Huge Helmet']},
    'Upper West Wing of the Temple of Fire' : {
        CUTSCENE: True,
        COLOR: 'RED',
        SPRITE: 'fire temple',
        DESC: 'a room full of dummies and targets.',
        NORTH: 'Chamber of Ignisius',
        SOUTH: 'Middle West Wing of the Temple of Fire',
        CREATURES: ['Juggernaut of the Temple of Fire'],
        GROUND: []},
    'Chamber of Ignisius' : {
        CUTSCENE: True,
        COLOR:'RED',
        SPRITE: 'fire temple',
        DESC:'quite the epic battleground.',
        EAST:'Mountain Pass',
        CREATURES: ['Ignisius, Sheppard of the Temple of Fire'],
        GROUND: []},
    'Mountain Pass' : {
        COLOR: 'YELLOW',
        SPRITE: 'cave',
        DESC: 'A path past several mountains, connecting mount falco and Gaea\'s pass. it ends by a deep hole, leading to the entrance of the cave system. it\'s quite the leap, so if you go down you won\'t ever go back to mount falco.',
        WEST: 'Chamber of Ignisius',
        DOWN: 'Not So Mysterious hole',
        CREATURES: [],
        GROUND: []},
    'Not So Mysterious hole' : {
        CUTSCENE: True,
        SPRITE: 'cave',
        COLOR: 'YELLOW',
        DESC: '',
        CREATURES: [],
        GROUND: []},
    'Nate\'s Room' : {
        CUTSCENE: True,
        LOCKED: True,
        COLOR: 'CYAN',
        SPRITE: 'inside',
        DESC: 'A small room, with only the basics.',
        DOWN: 'The Grey Horse Tavern',
        CREATURES: ['Nate'],
        GROUND: []},
    'Chicken City' : {
        SPRITE: 'forest',
        DESC: 'A city inhibited by chickens, surrounded by mesh wire after the great chicken war.',
        WEST: 'Midori Forest',
        EAST: 'Midori Forest',
        SOUTH: 'Midori Forest',
        NORTH: 'Midori Forest',
        CREATURES: ['Chicken Beast'],
        GROUND: []},
    'Cottage of the Witch Man' : {
        DESC: 'A cottage in the middle of Midori Forest',
        SPRITE: 'forest',
        WEST: 'Midori Forest',
        EAST: 'Midori Forest',
        SOUTH: 'Midori Forest',
        NORTH: 'Midori Forest',
        CREATURES: ['The Witch Man'],
        GROUND: []},
    'Realm of the Unicorns' : {
        DESC: 'A world in the clouds, fallen when the airdragon dissapeared and could no longer maintain his home.',
        SPRITE: 'clouds',
        DOWN: 'Midori Forest',
        CREATURES: ['Unicorn'],
        GROUND: []},
    'Cave Entrance' : {
        COLOR: 'YELLOW',
        SPRITE: 'street',
        DESC: 'The entrance to a large cave network. there is a faint light coming from the ceiling, but it\'s out of reach.',
        WEST: 'Town Exit East',
        NORTH: 'Forgotten Paths ',
        CREATURES: [],
        GROUND: []},
    'Forgotten Paths ' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'With close to none light it is hard to see where you are. Silence roams in the cave. A faint duff smell fills your nose as you walk your way through the tunnels',
        NORTH:'Lost Stones',
        WEST:'Soulles Trench',
        SOUTH:'Cave Entrance',
        CREATURES:[],
        GROUND: ['Miner\'s Helmet']},
   'Lost Stones' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'With close to none light it is hard to see where you are. Up East you see faint light shimmering through the tunnel.',
        EAST: 'Gate of Dredgen Arath',
        WEST:'Empty terrain',
        SOUTH:'Forgotten Paths ',
        CREATURES:[],
        GROUND: []},
    'Soulles Trench' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'With close to none light it is hard to see where you are. Silence roams in the cave. A faint duff smell fills your nose as you walk your way through the tunnels',
        NORTH:'Empty terrain',
        EAST: 'Forgotten Paths ',
        CREATURES:[],
        GROUND: []},
    'Empty terrain' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'With close to none light it is hard to see where you are. Silence roams in the cave. A faint duff smell fills your nose as you walk your way through the tunnels',
        EAST: 'Lost Stones',
        SOUTH:'Soulles Trench',
        CREATURES:[],
        GROUND: []},
    'Gate of Dredgen Arath' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'The ground you walk on has itself covered with the remnants of animals. You faintly smell blood, which is everything but inviting. Upon entering the gate you spot a lonely goblin searching on the ground. You try to hide before it notices you, sadly enough you fail. Golbins have a quite aggresive personality.',
        NORTH:'Horns divided',
        EAST: 'Steps of Dredgen Kahn',
        WEST:'Lost Stones',
        SOUTH:'Hall of Dredgen Yor',
        CREATURES:['Young Goblin Scout'],
        GROUND: []},
    'Steps of Dredgen Kahn' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'The ground you walk on has itself covered with the remnants of animals. You faintly smell blood, which is everything but inviting.',
        WEST:'Gate of Dredgen Arath',
        CREATURES:[],
        GROUND: []},
    'Hall of Dredgen Yor' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'The ground you walk on has itself covered with the remnants of animals. You faintly smell blood, which is everything but inviting.',
        NORTH:'Gate of Dredgen Arath',
        EAST: 'Sanctuem of Bones',
        CREATURES:[],
        GROUND: []},
    'Sanctuem of Bones' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'The ground you walk on has itself covered with the remnants of animals. You faintly smell blood, which is everything but inviting.',
        WEST:'Hall of Dredgen Yor',
        CREATURES:[],
        GROUND: []},
    'Goblin Cave' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'One thing you faguely remember about goblins is that they have an excellent smell, and their blood on your clothes does reek.',
        NORTH:'Goblin settlement',
        WEST:'Horns divided',
        CREATURES:['Young Goblin Scout','Veteran Goblin Scout'],
        GROUND: []},
    'Goblin settlement' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'You follow the light at the end of the tunnel and you find yourself visiting a goblin settlement. The building\'s are smaller and more circular than you expected. The blood on your clothes attracts the goblins.',
        NORTH:'Goblin Townhall',
        WEST:'Abandoned town square',
        SOUTH:'Goblin Cave',
        CREATURES:['Young Goblin Scout','Veteran Goblin Scout','Goblin Hunter'],
        GROUND: []},
    'Goblin Townhall' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'You stand before what you think is a townhall. It is bigger than most building\'s in this area.',
        WEST:'Goblin Watchtower',
        SOUTH:'Goblin settlement',
        CREATURES:['Veteran Goblin Scout','Goblin Hunter','Goblin Swordsman'],
        GROUND: []},
    'Abandoned town square' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'The only cubic building in the town. You feel uncomfortable entering the building in front of you. Something sinister resides in the building',
        NORTH:'Goblin Watchtower',
        SOUTH:'Cubic Building',
        CREATURES:['Young Goblin Scout','Goblin Hunter','Goblin Shaman'],
        GROUND: []},   
    'Cubic Building' : {
        COLOR:'YELLOW',
        SPRITE: 'inside',
        DESC:'You thought Goblins were nothing more but animals, yet you see here in front of you 2 goblins playing something resembling chess. You realise you made a terrible mistake afer you make eye contact with one of them.',
        NORTH:'Abandoned town square',
        CREATURES:['Goblin Warchief','Goblin Sorcerer'],
        GROUND: []},
    'Goblin Watchtower' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'You stand at the edge of the town. You don\'t know what\'s more inviting. The bloody massacre behind you or the immense battlefield in front of you.',
        EAST: 'Goblin Townhall',
        WEST:'The Raging War South',
        SOUTH:'Abandoned town square',
        CREATURES:['Goblin Swordsman','Goblin Hunter','Young Goblin Scout','Veteran Goblin Scout'],
        GROUND: []},
    'Horns divided' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'You face 2 tunnels, one filled with traces of goblins, the other is very long and filled with a omnimous silence and a strange aura.',
        EAST:'Goblin Cave',
        WEST:'Grove of Horu\'usk',
        SOUTH:'Gate of Dredgen Arath',
        CREATURES:[],
        GROUND: []}, 
    'Grove of Horu\'usk' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'The place you enter is nothing like the other parts of the cave. You enter some sort of grove. Grass and trees grow in this part of the cave system. The trees must be thousands of years old. The grass and trees are not of natural color, they have a more white and shining appearence. Their also resides a huge rock in this cave, or so you thought...',
        NORTH:'Godless Altar',
        EAST: 'Horns divided',
        WEST:'Felwinter\'s Refuge',
        CREATURES:['Rock Golem'],
        GROUND: []},
    'Godless Altar' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'Hidden behind some stones stands an amazingly crafted altar. The altar looks godly, which only makes you wonder to which god this altar belonged too. Judging from the age of this place it must have been for one of the old gods.',
        WEST:'Tree of Gaea',
        SOUTH:'Grove of Horu\'usk',
        CREATURES:[],
        GROUND: []},
    'Felwinter\'s Refuge' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'As you walk your way through this beautifull place you stumble upon a small cave. Upon entering the cave you notice that this cave was once inhabited. A single person seems to have liven here. Judging by the skeleton resting in the middle of the cave it must have been years since this person died. Looking in the cave you spot a diary. Upon closer inspection you figure out a certain "felwinter" took his refuge in this cave.',
        NORTH:'Tree of Gaea',
        EAST: 'Grove of Horu\'usk',
        CREATURES:[],
        GROUND: ['Felwinter\'s lie']},
    'Tree of Gaea' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'The grass and trees do not grow in this area, strangly enough one large tree remains in the middle of this area. The tree looks define, but at closer inspection you see that the tree is dying.',
        NORTH:'The Raging War West',
        EAST: 'Godless Altar',
        SOUTH:'Felwinter\'s Refuge',
        CREATURES:[],
        GROUND: []},
    'The Raging War South' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'Golems and Goblins are fighting each other. The battle is one of a kind in which that no red blood is spilled. Only the purple blood of Goblins and the crumbling of stones. Anyone not used to the smell of death would have passed out at this point. Yet you stand here, watching one of the things you never hoped to see.',
        NORTH:'The Raging War East',
        EAST: 'Goblin Watchtower',
        WEST:'The Raging War West',
        CREATURES:['Angry Golem'],
        GROUND: []},
    'The Raging War West' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'Golems and Goblins are fighting each other. The battle is one of a kind in which that no red blood is spilled. Only the purple blood of Goblins and the crumbling of stones. Anyone not used to the smell of death would have passed out at this point. Yet you stand here, watching one of the things you never hoped to see.',
        NORTH:'The Raging War North',
        EAST: 'The Raging War South',
        SOUTH:'Tree of Gaea',
        CREATURES:['Goblin Warknight'],
        GROUND: []},
    'The Raging War North' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'Golems and Goblins are fighting each other. The battle is one of a kind in which that no red blood is spilled. Only the purple blood of Goblins and the crumbling of stones. Anyone not used to the smell of death would have passed out at this point. Yet you stand here, watching one of the things you never hoped to see.',
        EAST: 'The Raging War East',
        SOUTH:'The Raging War West',
        CREATURES:['Goblin Warknight'],
        GROUND: []},
    'The Raging War East' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'Golems and Goblins are fighting each other. The battle is one of a kind in which that no red blood is spilled. Only the purple blood of Goblins and the crumbling of stones. Anyone not used to the smell of death would have passed out at this point. Yet you stand here, watching one of the things you never hoped to see.',
        EAST: 'Earth\'s void',
        SOUTH:'The Raging War South',
        WEST:'The Raging War North',
        CREATURES:['Angry Golem'],
        GROUND: []},
    'Earth\'s void': {
        CUTSCENE: True, 
        COLOR:'MAGENTA',
        SPRITE: 'cave',
        DESC:'The war does not take place here, which is not strange considering the immense aura you\'re feeling up ahead. From your previous experiences you know what creatures can produce this feeling. Dragons. ',
        DOWN: 'Gaea\'s lair',
        WEST:'The Raging War East',
        CREATURES:[],
        GROUND: []},
    'Gaea\'s lair' : {
        COLOR:'YELLOW',
        SPRITE: 'cave',
        DESC:'',
        UP: 'Earth\'s void',
        CREATURES:['Gaea, of a Thousand Grounds'],
        GROUND: []},
    'Shore' :   {
        COLOR:'CYAN',
        SPRITE: 'beach',
        DESC:'A couple of meters away from the beach, the water starts to flow around your feet, you see some seagulls fly above your head and there appears to be a big boat in the distance.',
        EAST:'Beach',
        WEST:'Open Sea',
        CREATURES: [],
        GROUND: []},
    'Open Sea' :    {
        COLOR:'BLUE',
        SPRITE: 'beach',
        DESC:'You are unable to walk on solid ground now, from her on out you\'ll have to swim to make progress, when you look down you start seeing some small fish, hoping to find something to eat.',
        EAST:'Shore',
        WEST:'Ocean',
        #SOUTH:'Deeper Sea',
        CREATURES: [],
        GROUND: []},
    'Ocean' :   {
        COLOR:'BLUE',
        SPRITE: 'beach',
        DESC:'You are just barely able to see the bottom of the ocean here, its pretty deep',
        EAST:'Ocean',
        SOUTH:'Deep Ocean',
        CREATURES: ['Shark'],
        GROUND: []},
    'Reef' :    {
        COLOR:'BLUE',
        SPRITE: 'underwater',
        DESC:'A beautiful mixture of colors hidden underwater, pretty fish are swimming around you, this truly is one of the prettiest places you have ever seen.',
        NORTH:'Open Sea',
        WEST:'Deep Ocean',
        CREATURES: [],
        GROUND: ['Sea Anemone']},
    'Deep Ocean' :  {
        COLOR:'BLUE',
        SPRITE: 'underwater',
        DESC: 'Extremely deep waters, rumor has it that there is a giant octopus who is making the water unsafe for each and every animal that decides to swim in it',
        NORTH: 'Ocean',
        EAST: 'Reef',
        CREATURES: ['Octopus'],
        GROUND: []},
    'Trench' :  {
        COLOR:'BLUE',
        SPRITE: 'underwater',
        DESC: 'The lowest points on earth\'s surface are located in trenches like these, several kilometers deep with weird and undiscovered creatures that will cross your path if you decide to go down in it',
        NORTH: 'Deep Ocean',
        DOWN: 'Glaucus\'s Gates',
        CREATURES: ['Sharktopus'],
        GROUND: ['Sunken Ship Wreck']},
    'Glaucus\'s Gates' : {
        CUTSCENE: True,
        COLOR:'YELLOW',
        SPRITE: 'underwater temple',
        DESC: 'A hidden doorway got you into the Gates of Glaucus, you find yourself in a beautiful, shiny gold temple hidden several kilometers under the water surface',
        UP: 'Trench',
        EAST: 'Northeastern Corner',
        WEST: 'Northwestern Corner',
        CREATURES: [],
        GROUND: []},
    'Northeastern Corner':  {
        COLOR:'YELLOW',
        SPRITE: 'underwater temple',
        DESC:'You find yourself in the Northeastern Corner of the temple',
        SOUTH:'Pufferpath', 
        WEST:'Glaucus\'s Gates',
        CREATURES: [],
        GROUND: []},
    'Northwestern Corner':  {
        COLOR:'YELLOW',
        SPRITE: 'underwater temple',
        DESC:'You find yourself in the Northwestern Corner of the temple',
        SOUTH:'Jellylane',
        EAST:'Glaucus\'s Gates',
        CREATURES: [],
        GROUND: []},
    'Southwestern Corner':  {
        COLOR:'YELLOW',
        SPRITE: 'underwater temple',
        DESC:'You find yourself in the Southwestern Corner of the temple',
        NORTH:'Jellylane',
        EAST:'Main Hall',
        CREATURES: [],
        GROUND: []},
    'Southeastern Corner': {
        COLOR:'YELLOW',
        SPRITE: 'underwater temple',
        DESC:'You find yourself in the Southeastern Corner of the temple',
        NORTH:'Pufferpath',
        WEST:'Main Hall',
        CREATURES: [],
        GROUND: []},
    'Pufferpath': {
        COLOR:'GREEN',
        SPRITE: 'underwater temple',
        DESC:'You walk an algae infested road like path from corner to corner, water splats each time you step further, it seems pretty safe but there are enemies waiting for perfect time to attack',
        NORTH:'Northeastern Corner',
        SOUTH:'Southeastern Corner',
        CREATURES: ['Pufferfish', 'Pufferfish'],
        GROUND: []},
    'Jellylane': {
        COLOR:'MAGENTA',
        SPRITE: 'underwater temple',
        DESC:'You are going to have to swim to the other side, the tubelike path you are located in is filled to the top with water, there is only one extra problem; there are multiple Jellyfish blocking your exit',
        NORTH:'Northeastern Corner',
        SOUTH:'Southeastern Corner',
        CREATURES: ['Jellyfish', 'Jellyfish', 'Jellyfish'],
        GROUND: []},
    'Main Hall': {
        COLOR:'YELLOW',
        SPRITE: 'underwater temple',
        DESC: 'A beautiful golden hall gets shown when you enter, there is nothing there apart from the golden walls, ceiling and even the rug on the floor is sprinkled with golddust. There seems to be a hidden hatch underneath it, hiding a passage underneath.',
        NORTH:'Brucy\'s Cavern',
        EAST:'Southeastern Corner',
        WEST:'Southwestern Corner',
        DOWN:'Poseidon\'s Passage',
        CREATURES: [],
        GROUND: []},
    'Brucy\'s Cavern': {
        COLOR:'BLUE',
        SPRITE: 'underwater temple',
        DESC: 'You\'re underwater again, you seem to be in a mined out sculpture in the side of the Trench, something about the aura of the place does not feel right, it seems like you are not alone...',
        SOUTH:'Main Hall',
        CREATURES: ['Bruce'],
        GROUND: ['Shark Tooth']},
    'Poseidon\'s Passage': {
        CUTSCENE: True,
        COLOR:'YELLOW',
        SPRITE: 'underwater temple',
        DESC:'A longstretched path lies in front of you, no gold this time, just a long tunnel with something at the end of it, that something is unclear, for now...',
        SOUTH:'Northern Shark Isle',
        UP:'Main Hall',
        CREATURES: [],
        GROUND: ['Poseidon\'s Trident']},
    'Northern Shark Isle': {
        COLOR:'BLUE',
        SPRITE: 'underwater temple',
        DESC:'Another long road waits ahead, partially filled with dirty looking water which you cannot see through, all the information you\'ve got is the name of the road, displayed on the name sign to your right: Shark Isle.',
        NORTH:'Poseidon\'s Pathway',
        SOUTH:'Southern Shark Isle',
        CREATURES: ['Shark', 'Small Shark', 'Small Shark', 'Big Shark'],
        GROUND: []},
    'Southern Shark Isle': {
        COLOR:'BLUE',
        SPRITE: 'underwater temple',
        DESC:'You are half way there, there is no reason to hope that you will not have to fight anymore sharks today, you can see their empty black eyes a fraction above the surface level staring at you.',
        NORTH:'Northern Shark Isle',
        SOUTH:'Glaucus\'s Monument',
        CREATURES: ['Big Shark', 'Big Shark', 'Shark', 'Shark', 'Small Shark'],
        GROUND: ['Sea Broccoli']},
    'Glaucus\'s Monument': {
        COLOR:'BLUE',
        SPRITE: 'underwater temple',
        DESC:'This seems to be end end of the Temple, no roads or paths leading from it besides the one you just came from, however, you don\'t see a dragon either...',
        NORTH:'Southern Shark Isle',
        UP: 'Deep Ocean',
        CREATURES: ['Glaucus the Water Dragon'],
        GROUND: []},
}
