from variables import *

"""
List of all creatures
"""

worldCreatures = {
    'Dummy' : {
        GROUNDDESC: 'A dummy.',
        SHORTDESC: 'The dummy',
        LONGDESC: 'A real dummy.',
        TALKABLE: True,
        GREETING: 'Hello, I am a real dummy.',
        GOLD: 5,
        HEALTH: 1,
        STRENGTH: 0,
        DEFENCE: 5,
        SPEED: 0,
        PERCEPTION: 0,
        MAXHEALTH: 1, 
        EXP: 15,
        SIDEQUEST: True,
        SIDEQUESTSTART: 'Can I haz Showd Swowd and Minow Health Potion plz uWu?',
        SIDEQUESTITEMS: ['Short Sword', 'Minor Health Potion'],
        SIDEQUESTEND: 'Thank u vewy, vewy much. *notices big swowd and awmow* Pwease take my big, heavy swowd and awmow :3!',
        SIDEQUESTREWARD: ['Great Sword','Leather Trousers','Leather Chestplate'],
        SIDEQUESTINV: [],
        DROPITEM: [],
        SPRITE: 'dummy',
        DESCWORDS: ['dummy']},
    'Depressed Pig' : {
        GROUNDDESC: 'A pig lazily lays on the ground.',
        SHORTDESC: 'The pig',
        LONGDESC: 'A fat pig which looks like it isn\'t long for this world.',
        TALKABLE: True,
        GREETING: 'Depressed Pig: Release me from my suffering.',
        GOLD: 1,
        HEALTH: 1,
        STRENGTH: 1,
        DEFENCE: 3,
        SPEED: 1,
        PERCEPTION: 0,
        MAXHEALTH: 1, 
        EXP: 50,
        SPRITE: 'depressed pig',
        DESCWORDS: ['pig', 'animal', 'depressed pig']},
    'Egar' : {
        GROUNDDESC: 'A giant Orc that could easily rip you in two stands behind the counter. He\'s wearing a novelty nametag in the shape of a sword with the name "Egar" written on it.',
        SHORTDESC: 'Egar',
        LONGDESC: 'Egar is a giant Orc with a large beard and a scar around his left eye. His weapon of choice is a great sword he gave a nickname "Betsy".',
        TALKABLE: True,
        GREETING: 'Egar: If you want weapons, I\'m your guy.',
        GOLD: 50,
        HEALTH: 50,
        STRENGTH: 25,
        DEFENCE: 18,
        SPEED: 7,
        PERCEPTION: 10,
        MAXHEALTH: 50, 
        EXP: 500,
        DESCWORDS: ['orc', 'egar']},
    'Derick' : {
        GROUNDDESC: 'A dwarf as wide as he is tall, but as strong as a giant.',
        SHORTDESC: 'Derick',
        LONGDESC: 'A dwarf as wide as he is tall, but as strong as a giant.',
        TALKABLE: True,
        GREETING: 'Derick: Come get your armor.',
        GOLD: 55,
        HEALTH: 45,
        STRENGTH: 23,
        DEFENCE: 20,
        SPEED: 15,
        PERCEPTION: 20,
        MAXHEALTH: 45, 
        EXP: 500,
        DESCWORDS: ['dwarf', 'derick']},
    'Madam Madame' : {
        GROUNDDESC: 'An Elven witch who seems to look right trough you.',
        SHORTDESC: 'Madam Madame',
        LONGDESC: 'An Elven witch who seems to look right trough you.',
        TALKABLE: True,
        GREETING: 'Madam Madame: It looks like you could use some of my magic.',
        GOLD: 100,
        HEALTH: 45,
        STRENGTH: 20,
        DEFENCE: 18,
        SPEED: 20,
        PERCEPTION: 20,
        MAXHEALTH: 45, 
        EXP: 500,
        DESCWORDS: ['elf', 'witch', 'madam madame']},
    'Gray Horse' : {
        GROUNDDESC: 'A large Centaur with a grey mane and coat.',
        SHORTDESC: 'Gray Horse',
        LONGDESC: 'A large Centaur with a grey mane and coat.',
        TALKABLE: True,
        GREETING: 'Gray Horse: You want somethin\' strong to forget you here?',
        GOLD: 50,
        HEALTH: 55,
        STRENGTH: 25,
        DEFENCE: 18,
        SPEED: 25,
        PERCEPTION: 20,
        MAXHEALTH: 55, 
        EXP: 500,
        DESCWORDS: ['centaur', 'gray horse', 'barman']},
    'Wild Frog' : {
        GROUNDDESC: 'A big frog jumps out of the grass.',
        SHORTDESC: 'The wild frog',
        LONGDESC: 'A wild frog croaks a rythmless tune.',
        TALKABLE: True,
        GREETING: 'Wild frog: Ribbit.',
        GOLD: 0,
        HEALTH: 3,
        STRENGTH: 2,
        DEFENCE: 10,
        SPEED: 15,
        PERCEPTION: 3,
        MAXHEALTH: 3, 
        EXP: 75,
        DROPITEM: ['Frog Leg'],
        DESCWORDS: ['frog','wild frog']},
    'Wild Chicken' : {
        BOSS: True,
        GROUNDDESC: 'A crazy chicken jumps at you from a tree.',
        SHORTDESC: 'The Wild Chicken',
        LONGDESC: 'The wild chicken stares at you menacingly.',
        TALKABLE: True,
        GREETING: 'Wild chicken: *violent chicken noises*',
        GOLD: 3,
        HEALTH: 10,
        STRENGTH: 7,
        DEFENCE: 5,
        SPEED: 30,
        PERCEPTION: 4,
        MAXHEALTH: 10, 
        EXP: 100,
        DROPITEM: ['Feathers'],
        DESCWORDS: ['chicken', 'wild chicken', 'crazy chicken']},
    'Wild Cow' : {
        GROUNDDESC: 'A fat cow is ruminating some grass in a meadow.',
        SHORTDESC: 'The wild cow',
        LONGDESC: 'The wild cow stares into the abyss.',
        TALKABLE: True,
        GREETING: 'Cow: Mooh',
        GOLD: 10,
        HEALTH: 35,
        STRENGTH: 2,
        DEFENCE: 1,
        SPEED: 3,
        PERCEPTION: 0,
        MAXHEALTH: 35, 
        EXP: 115,
        DROPITEM: ['Cow Hide'],
        DESCWORDS: ['cow', 'wild cow', 'fat cow']},
    'Wild Wolf' : {
        GROUNDDESC: 'A black wolf sneaks up from behind you.',
        SHORTDESC: 'The wild wolf',
        LONGDESC: 'The wild wolf growls at you with it\'s bare teeth.',
        TALKABLE: True,
        GREETING: 'Wolf: Grrr',
        GOLD: 15,
        HEALTH: 20,
        STRENGTH: 12,
        DEFENCE: 3,
        SPEED: 10,
        PERCEPTION: 10,
        MAXHEALTH: 20, 
        EXP: 175,
        DROPITEM: ['Wolf Fang'],
        DESCWORDS: ['wolf', 'wild wolf', 'black wolf']},
    'Chicken Beast' : {
        BOSS: True,
        GROUNDDESC: 'A massive chicken wearing wooden armor comes charging towards you. "for too long have humans locked us away in our city using wire netting! today we will fight back!',
        SHORTDESC: 'The Chicken Beast',
        LONGDESC: 'That armor should break with a few hits.',
        TALKABLE: True,
        GREETING: 'Chicken Beast: "cock-a-doodle-doooo!"',
        GOLD: 5,
        HEALTH: 30,
        STRENGTH: 5,
        DEFENCE: 8,
        SPEED: 10,
        PERCEPTION: 2,
        MAXHEALTH: 30, 
        EXP: 125,
        DROPITEM: ['Beast Egg'], 
        DESCWORDS: ['chicken', 'chicken beast', 'massive chicken']},    
    'The Witch Man' : {
        BOSS: True,
        GROUNDDESC: 'An old looking man wielding two swords jumps from a horse. He screams "Praise me, for I am the Witch Man!"',
        SHORTDESC: 'The Witch Man',
        LONGDESC: 'He looks like a saint that took to much health potions.',
        TALKABLE: True,
        GREETING: 'The Witch Man: I am the hero of the people!',
        GOLD: 8,
        HEALTH: 32,
        STRENGTH: 8,
        DEFENCE: 8,
        SPEED: 8,
        PERCEPTION: 8,
        MAXHEALTH: 32, 
        EXP: 160,
        DROPITEM: ['Hidden Gem'], 
        DESCWORDS: ['witch man']},
    'Unicorn' : {
        BOSS: True,
        GROUNDDESC: 'A Unicorn approaches you.',
        SHORTDESC: 'The Unicorn',
        LONGDESC: 'The Unicorn seems lost in this deteriorating world.',
        TALKABLE: True,
        GREETING: 'Unicorn: We have been living in fear ever since your kind took him away from us.',
        GOLD: 50,
        HEALTH: 30,
        STRENGTH: 10,
        DEFENCE: 8,
        SPEED: 10,
        PERCEPTION: 10,
        MAXHEALTH: 30, 
        EXP: 200,
        DROPITEM: ['Unicorn Hair'],
        DESCWORDS: ['unicorn']},
    'Glaucus the Water Dragon' : {
        DRAGON: True,
        GROUNDDESC: 'Glaucus, ruler of of the sea',
        SHORTDESC: 'Water Dragon',
        LONGDESC: 'A majestic animal, covered in a skin made of the most pretty shade of blue dabadee dabadaa you have ever seen.',
        TALKABLE: True,
        GREETING: 'Its for the greater good',
        GOLD: 0,
        HEALTH: 10,
        STRENGTH: 0,
        DEFENCE: 0,
        SPEED: 1,
        PERCEPTION: 1,
        MAXHEALTH: 10, 
        EXP: 150,
        DESCWORDS: ['dragon', 'waterdragon', 'glaucus']},
    #'Ingrid' : {
    #    GROUNDDESC: ''
    #}
    'Urila' : {
        GROUNDDESC: 'Urila.',
        SHORTDESC: 'Urila',
        LONGDESC: 'Urila.',
        TALKABLE: True,
        GREETING: 'Hello, I am Urila.',
        GOLD: 45,
        HEALTH: 35,
        STRENGTH: 15,
        DEFENCE: 15,
        SPEED: 15,
        PERCEPTION: 15,
        MAXHEALTH: 35, 
        EXP: 300,
        SIDEQUEST: True,
        SIDEQUESTSTART: 'Hey, if you give me five frog legs, feathers, cow hides, wolf fangs and unicorn hairs, I\'ll give you something really cool.',
        SIDEQUESTITEMS: ['Frog Leg', 'Frog Leg', 'Frog Leg', 'Frog Leg', 'Frog Leg', 'Feathers', 'Feathers', 'Feathers', 'Feathers', 'Feathers', 'Cow Hide', 'Cow Hide', 'Cow Hide', 'Cow Hide', 'Cow Hide', 'Wolf Fang', 'Wolf Fang', 'Wolf Fang', 'Wolf Fang', 'Wolf Fang', 'Unicorn Hair', 'Unicorn Hair', 'Unicorn Hair', 'Unicorn Hair', 'Unicorn Hair'],
        SIDEQUESTEND: 'With all the items you have given me I\'m able to create the True Surviver Armor.',
        SIDEQUESTREWARD: [''],
        SIDEQUESTINV: [],
        DROPITEM: [],
        DESCWORDS: ['urila']},
    'Nate' : {
        GROUNDDESC: 'Nate.',
        SHORTDESC: 'Nate',
        LONGDESC: 'Nate.',
        TALKABLE: True,
        GREETING: 'Hello, I am Nate',
        GOLD: 5,
        HEALTH: 1,
        STRENGTH: 0,
        DEFENCE: 5,
        SPEED: 0,
        PERCEPTION: 0,
        MAXHEALTH: 1, 
        EXP: 15,
        DROPITEM: [],
        DESCWORDS: ['nate']},  
    'Lounge of Fire Lizards' : {
        GROUNDDESC: 'A lounge of Fire Lizards is hanging out in a puddle of lava.',
        SHORTDESC: 'The lounge of Fire Lizards',
        LONGDESC: 'The Fire Lizards make some squeaking noises.',
        TALKABLE: True,
        GREETING: 'Fire Lizard: Squeak.',
        GOLD: 3,
        HEALTH: 3,
        STRENGTH: 3,
        DEFENCE: 20,
        SPEED: 15,
        PERCEPTION: 2,
        MAXHEALTH: 3, 
        EXP: 75,
        DROPITEM: ['Fried Lizard'], 
        DESCWORDS: ['lounge of fire lizards', 'fire lizards', 'lizards']},
    'Lava Snail' : {
        GROUNDDESC: 'A Lava Snail wanders around.',
        SHORTDESC: 'the Lava Snail',
        LONGDESC: 'The Lava Snail leaves a trail of glowing molten rocks behind.',
        TALKABLE: True,
        GREETING: 'The Lava Snail remains silent',
        GOLD: 20,
        HEALTH: 30,
        STRENGTH: 4,
        DEFENCE: 2,
        SPEED: 2,
        PERCEPTION: 1,
        MAXHEALTH: 30, 
        EXP: 200,
        DESCWORDS: ['lava snail', 'snail']},
    'Rock Golem' : { 
        GROUNDDESC: 'A boulder turns around, revealing it\'s face. You are facing a 20 meter long golem. Moss is growing on its body, showing how long it has stayed in his current position. The golem somehow leaves a calm and patience impression on you',
        SHORTDESC: 'The Rock Golem',
        LONGDESC: 'The Rock Golem awaits your actions patiently', 
        TALKABLE: True,
        GREETING:'The Rock golem remains silent', 
        GOLD: 25,
        HEALTH: 70,
        STRENGTH: 30,
        DEFENCE: 2,
        SPEED: 2,
        PERCEPTION: 1, 
        MAXHEALTH: 70,
        EXP: 300, 
        DESCWORDS:['Rock Golem','Golem','Thing', 'rock golem', 'golem']},
    'Young Goblin Scout' : { 
        BOSS: True,
        GROUNDDESC: 'A young goblin scout searches the ground for goods.',
        SHORTDESC: 'A goblin',
        LONGDESC: 'The goblin notices your presence and takes on an offensive stance', 
        TALKABLE: True,
        GREETING:'The Goblin screeches', 
        GOLD: 30,
        HEALTH: 4,
        STRENGTH: 6,
        DEFENCE: 6,
        SPEED: 25,
        PERCEPTION: 3, 
        MAXHEALTH: 10,
        EXP: 125, 
        DESCWORDS:['Goblin','goblin', 'Young Goblin Scout', 'young goblin scout']},
    'Veteran Goblin Scout' : { 
        GROUNDDESC: 'The veteran goblin scout looks tirelessly around himself to spot anything valueable.',
        SHORTDESC: 'A goblin',
        LONGDESC: 'The goblin notices your presence and takes on an offensive stance', 
        TALKABLE: True,
        GREETING:'The Goblin screeches', 
        GOLD: 30,
        HEALTH: 32,
        STRENGTH: 7,
        DEFENCE: 7,
        SPEED: 25,
        PERCEPTION: 3, 
        MAXHEALTH: 32,
        EXP: 125, 
        DESCWORDS:['Goblin','goblin', 'Veteran Goblin Scout', 'veteran goblin scout']},
    'Goblin Hunter' : { 
        GROUNDDESC: 'The goblin hunter feels more collected then those you encountered before.',
        SHORTDESC: 'A goblin',
        LONGDESC: 'The goblin notices your presence and takes on an offensive stance', 
        TALKABLE: True,
        GREETING:'Go... away...', 
        GOLD: 35,
        HEALTH: 20,
        STRENGTH: 10,
        DEFENCE: 5,
        SPEED: 30,
        PERCEPTION: 5, 
        MAXHEALTH: 20,
        EXP: 125, 
        DESCWORDS:['Goblin','goblin', 'Goblin Hunter', 'goblin hunter']},
    'Goblin Swordsman' : { 
        BOSS: True,
        GROUNDDESC: 'The goblin swordsman draws a sword after noticing you.',
        SHORTDESC: 'A goblin',
        LONGDESC: 'The goblin notices your presence and points his sword at you.', 
        TALKABLE: True,
        GREETING:'BEGONE HUMAN', 
        GOLD: 30,
        HEALTH: 45,
        STRENGTH: 15,
        DEFENCE: 8,
        SPEED: 12,
        PERCEPTION: 1, 
        MAXHEALTH: 45,
        EXP: 150, 
        DESCWORDS:['Goblin','goblin','goblin swordsman','Goblin Swordsman']},
    'Goblin Warknight' : { 
        GROUNDDESC: 'You see how a Goblin Warknight takes the life of the goblin.',
        SHORTDESC: 'A goblin',
        LONGDESC: 'The goblin notices your presence and points his sword at you.', 
        TALKABLE: True,
        GREETING:'BEGONE HUMAN', 
        GOLD: 30,
        HEALTH: 45,
        STRENGTH: 15,
        DEFENCE: 8,
        SPEED: 12,
        PERCEPTION: 1, 
        MAXHEALTH: 45,
        EXP: 150, 
        DESCWORDS:['Goblin','goblin', 'Goblin Warknight, goblin warknight.']},
    'Angry Golem' : { 
        GROUNDDESC: 'A goblin is killed by a very Agry Golem.',
        SHORTDESC: 'A Golem',
        LONGDESC: 'The Golem notices your presence.', 
        TALKABLE: True,
        GREETING:'The golem remains silent', 
        GOLD: 30,
        HEALTH: 50,
        STRENGTH: 20,
        DEFENCE: 10,
        SPEED: 3,
        PERCEPTION: 1, 
        MAXHEALTH: 60,
        EXP: 200, 
        DESCWORDS:['Golem','golem', 'Angry Golem', 'angry golem']},
    'Goblin Shaman' : { 
        GROUNDDESC: 'An interesting dressed goblin shaman looks right through you.',
        SHORTDESC: 'A goblin',
        LONGDESC: 'You can smell an odd aroma coming from the Shaman.', 
        TALKABLE: True,
        GREETING:'Why do you cause disturbance here human, your presence is not wanted. Leave.', 
        GOLD: 5,
        HEALTH: 10,
        STRENGTH: 30, 
        DEFENCE: 5,
        SPEED: 20,
        PERCEPTION: 10, 
        MAXHEALTH: 30,
        EXP: 175, 
        DESCWORDS:['Goblin','goblin','goblin shaman','Goblin Shaman']},
    'Goblin Sorcerer' : { 
        BOSS: True, 
        GROUNDDESC: 'The goblin sorcerer exerts a huge amount of spiritual pressure.',
        SHORTDESC: 'A goblin',
        LONGDESC: 'The old goblin standing in front of you looks fragile, but something is giving you the feeling of great dread.', 
        TALKABLE: True,
        GREETING:'Fool, do you not understand the impact of your actions. Have you not thought at what cost you have slayed our children? Face your judgement.', 
        GOLD: 50,
        HEALTH: 100,
        STRENGTH: 12, 
        DEFENCE: 15,
        SPEED: 10,
        PERCEPTION: 15, 
        MAXHEALTH: 100,
        EXP: 500, 
        DESCWORDS:['Goblin','goblin','goblin sorcerer','Goblin Sorcerer']},
        #drop item needs to be something magical like an enchanted sword or something. 
    #'Spooky Boys'
    'Skeleton' : {  
        GROUNDDESC: 'bones from the ones you have slayed.',
        SHORTDESC: 'A skeleton',
        LONGDESC: 'A skeleton summoned by the Goblin Sorcerer.', 
        TALKABLE: True,
        GREETING:'Skeleton noise.', 
        GOLD: 0,
        HEALTH: 5,
        STRENGTH: 5, 
        DEFENCE: 5,
        SPEED: 10,
        PERCEPTION: 5, 
        MAXHEALTH: 5,
        EXP: 10, 
        DESCWORDS:['Skeleton','skeleton','spooky boy','Spooky Boy']},
    'Goblin Warchief': { 
        BOSS: True, 
        GROUNDDESC: 'The goblin warchief holds a broadsword the size of your torso, you feel shivers down your spine.',
        SHORTDESC: 'A goblin',
        LONGDESC: 'Before you stands a huge goblin. Scars mark his body. You have the feeling he could break your neck with two fingers.', 
        TALKABLE: True,
        GREETING:'To come to us in this time of turmoil, are you not aware of the ongoing war, human? Is this your race\'s dignity? To attack when one is already at war? For once i shall give my attention to a worm.', 
        GOLD: 50,
        HEALTH: 120,
        STRENGTH: 60, 
        DEFENCE: 25,
        SPEED: 5,
        PERCEPTION: 1, 
        MAXHEALTH: 120,
        EXP: 500, 
        DESCWORDS:['Goblin','goblin','goblin warchief','Goblin Warchief']},
    'Gaea, of a Thousand Grounds' : {
        DRAGON: True, 
        BOSS: True, 
        GROUNDDESC: 'The eyes of the ancient dragon lay upon your soul. It can see your mind being controlled by fear',
        SHORTDESC: 'Gaea, of a Thousand Grounds',
        LONGDESC: 'The scales of the dragon do not fit the normal description of scales. The scales itself look like they have individual life itself, moss is growing on them and from point to point tree branches are growing. This all on a solid structure resembling stone. The dragons body is completely covered in these scales. More impressing than the scales on its body, is the immense pressure the dragon is exerting.', 
        TALKABLE: True,
        GREETING:'Tell me human, Are you the one that slayed my brothers? Are you the one that caused disturbance in this world?', 
        GOLD: 125,
        HEALTH: 100,
        STRENGTH: 40,
        DEFENCE: 10,
        SPEED: 15,
        PERCEPTION: 7,
        MAXHEALTH: 60,
        EXP: 750,
        DESCWORDS:['dragon','gaea']},
    'Ignisius, Sheppard of the Temple of Fire' : {
        DRAGON: True, 
        BOSS: True, 
        GROUNDDESC: 'The dragon jumps towards you, breathing fire.',
        SHORTDESC: 'Ignisius, Sheppard of the Temple of Fire',
        LONGDESC: 'The dragon has no wings, but four claws that it swiftly runs around on. It doesn\'t seem to suffer from touching the magma. His tongue is constantly on fire, making flash flames shoot out of his mouth whenever he blows.', 
        TALKABLE: True,
        GREETING:'Are you prepared to spend the rest of your life praising me as if i were a god?', 
        GOLD: 150,
        HEALTH: 50,
        STRENGTH: 100, 
        DEFENCE: 50,
        SPEED: 40,
        PERCEPTION: 10, 
        MAXHEALTH: 50,
        EXP: 1000, 
        DESCWORDS:['dragon','ignisius']},
    'Aeres, the Northern Windcaller' : {
        DRAGON: True, 
        BOSS: True, 
        GROUNDDESC: 'Once a mighty dragon, now chained up in it\'s cage.',
        SHORTDESC: 'Aeres, the Northern Windcaller',
        LONGDESC: 'Aeres has mighty wings but they seem to be damaged. He has lost the will to fight.', 
        TALKABLE: True,
        GREETING:'"Human...". Aeres coughs and closes his eyes.', 
        GOLD: 15,
        HEALTH: 4,
        STRENGTH: 0, 
        DEFENCE: 0,
        SPEED: 0,
        PERCEPTION: 0, 
        MAXHEALTH: 4,
        EXP: 35, 
        DESCWORDS:['dragon','aeres']},
    'Ta\'xeq, Spawn of Death' : {
        DRAGON: True, 
        BOSS: True, 
        GROUNDDESC: 'The black, wingless dragon looks at you.',
        SHORTDESC: 'Ta\'xeq, Spawn of Death',
        LONGDESC: 'You now understand of what purpose this journey was. Ta\'xeq is the most dreadfull creature you have ever seen, and this resided under your home.', 
        TALKABLE: True,
        GREETING:'HOW LONG HAVE I WAITED. PREPARE TO FACE ME, TA\'XEQ, AND TREMBLE IN FEAR AS I WIPE YOUR PITFULL VILLAGE AWAY.', 
        GOLD: 150,
        HEALTH: 350,
        STRENGTH: 120, 
        DEFENCE: 70,
        SPEED: 10,
        PERCEPTION: 10, 
        MAXHEALTH: 350,
        EXP: 2000, 
        DESCWORDS:['dragon','taxeq','ta\'xeq']},
    
    'First Guardian of the Temple of Fire' : {
        BOSS: True,
        GROUNDDESC: 'A guard takes on an offensive stance.',
        SHORTDESC: 'The first guardian of the Temple of Fire',
        LONGDESC: 'Wielding a blazing spear, this guard looks like a challenge.',
        TALKABLE: True,
        GREETING: 'Guardian of the Temple of Fire: You\'ll perish in the name of Ignisius!',
        GOLD: 20,
        HEALTH: 50,
        STRENGTH: 20,
        DEFENCE: 15,
        SPEED: 20,
        PERCEPTION: 4,
        MAXHEALTH: 50, 
        EXP: 500,
        DESCWORDS: ['guardian of the temple of fire', 'guardian', 'guard', 'first guard', 'guard 1', 'first guardian', 'guardian 1']},
    'Second Guardian of the Temple of Fire' : {
        BOSS: True,
        GROUNDDESC: 'Another guard takes on a defensive stance.',
        SHORTDESC: 'The second guardian of the Temple of Fire',
        LONGDESC: 'Wielding a flaming sword and a shield of molten rock, this guard looks like a challenge.',
        TALKABLE: True,
        GREETING: 'Guardian of the Temple of Fire: You won\'t even get to see Ignisius!',
        GOLD: 20,
        HEALTH: 60,
        STRENGTH: 15,
        DEFENCE: 15,
        SPEED: 20,
        PERCEPTION: 4,
        MAXHEALTH: 50, 
        EXP: 500,
        DESCWORDS: ['guardian of the temple of fire', 'guardian', 'guard' 'second guard', 'guard 2', 'second guardian', 'guardian 2']},
    'Guardian of the Temple of Fire' : {
        BOSS: True,
        GROUNDDESC: 'A guard takes on an offensive stance.',
        SHORTDESC: 'The guardian of the Temple of Fire',
        LONGDESC: 'Wielding a flaming sword and a shield of molten rock, this guard looks like a challenge.',
        TALKABLE: True,
        GREETING: 'Guardian of the Temple of Fire: Fear the wrath of the Fire!',
        GOLD: 20,
        HEALTH: 50,
        STRENGTH: 20,
        DEFENCE: 15,
        SPEED: 20,
        PERCEPTION: 4,
        MAXHEALTH: 50, 
        EXP: 500,
        DESCWORDS: ['guardian of the temple of fire', 'guardian', 'guard']},
    'First Mage of the Temple of Fire' : {
        BOSS: True,
        GROUNDDESC: 'A mage summons a fireball.',
        SHORTDESC: 'The first mage of the Temple of Fire',
        LONGDESC: 'his robes look weak, but that\'s about anything weak about him.',
        TALKABLE: True,
        GREETING: 'Mage of the Temple of Fire: I foresee bad things for you.',
        GOLD: 20,
        HEALTH: 15,
        STRENGTH: 40,
        DEFENCE: 10,
        SPEED: 25,
        PERCEPTION: 10,
        MAXHEALTH: 15, 
        EXP: 500,
        DESCWORDS: ['mage of the temple of fire', 'mage', 'first mage', 'mage 1']},
    'Second Mage of the Temple of Fire' : {
        BOSS: True,
        GROUNDDESC: 'Another mage sets the floor ablaze.',
        SHORTDESC: 'The second mage of the Temple of Fire',
        LONGDESC: 'his robes are on fire but he doesn\'t seem to care.',
        TALKABLE: True,
        GREETING: 'Guardian of the Temple of Fire: time to roll up my sleeves.',
        GOLD: 20,
        HEALTH: 15,
        STRENGTH: 40,
        DEFENCE: 10,
        SPEED: 25,
        PERCEPTION: 8,
        MAXHEALTH: 15, 
        EXP: 500,
        DESCWORDS: ['mage of the temple of fire', 'mage', 'second mage', 'mage 2']},
    'Mage of the Temple of Fire' : {
        GROUNDDESC: 'A mage is reading a book.',
        SHORTDESC: 'The mage of the Temple of Fire',
        LONGDESC: 'he would probably be a strong opponent if he noticed you.',
        TALKABLE: True,
        GREETING: 'Guardian of the Temple of Fire: Fear the wrath of the Fire!',
        GOLD: 20,
        HEALTH: 50,
        STRENGTH: 20,
        DEFENCE: 15,
        SPEED: 20,
        PERCEPTION: 4,
        MAXHEALTH: 50, 
        EXP: 500,
        DESCWORDS: ['guardian of the temple of fire', 'guardian', 'guard']},
    'Archmage of the Temple of Fire' : {
        BOSS: False,
        GROUNDDESC: 'The archmage sits in his chair',
        SHORTDESC: 'The archmage of the Temple of Fire',
        LONGDESC: 'He does a cool trick with his wand.',
        TALKABLE: True,
        GREETING: 'Archmage of the Temple of Fire: "Knowledge is power, don\'t you agree?"',
        GOLD: 50,
        HEALTH: 50,
        STRENGTH: 35,
        DEFENCE: 15,
        SPEED: 0,
        PERCEPTION: 10,
        MAXHEALTH: 50, 
        EXP: 750,
        DESCWORDS: ['archmage of the temple of fire', 'archmage', 'mage']},
    'Juggernaut of the Temple of Fire' : {
        BOSS: False,
        GROUNDDESC: 'The juggernaut practices his uppercuts',
        SHORTDESC: 'The Juggernaut of the Temple of Fire',
        LONGDESC: 'He slams a dummy to the ground.',
        TALKABLE: True,
        GREETING: 'Juggernaut of the Temple of Fire: "I enjoy bashing skulls"',
        GOLD: 50,
        HEALTH: 100,
        STRENGTH: 10,
        DEFENCE: 20,
        SPEED: 1,
        PERCEPTION: 1,
        MAXHEALTH: 100, 
        EXP: 750,
        DESCWORDS: ['juggernaut of the temple of fire', 'juggernaut']},
    'Shark' : {
        GROUNDDESC: 'A medium sized shark attacks you from underneath',
        SHORTDESC: 'A shark',
        LONGDESC: 'A fish with teeth ready to rip you apart',
        TALKABLE: True,
        GREETING: 'Shark: blup',
        GOLD: 15,
        HEALTH: 20,
        STRENGTH: 12,
        DEFENCE: 3,
        SPEED: 10,
        PERCEPTION: 10,
        MAXHEALTH: 20, 
        EXP: 175,
        DESCWORDS: ['shark', 'medium shark']},
    'Big Shark' : {
        GROUNDDESC: 'A big shark slowly approaches you',
        SHORTDESC: 'A big shark',
        LONGDESC: 'Not a fish to mess around with this time, he could easily fit your entire body inside his',
        TALKABLE: True,
        GREETING: 'Big Shark: BLOOP',
        GOLD: 20,
        HEALTH: 30,
        STRENGTH: 20,
        DEFENCE: 5,
        SPEED: 5,
        PERCEPTION: 12,
        MAXHEALTH: 30, 
        EXP: 250,
        DESCWORDS: ['big shark',]},
    'Small Shark' : {
        SHARK: True,
        GROUNDDESC: 'A small sized shark has decided to attack you',
        SHORTDESC: 'A small shark shark',
        LONGDESC: 'The same intentions as his bigger assosciates, but by far not as dangerous',
        TALKABLE: True,
        GREETING: 'Small Shark: bluup',
        GOLD: 7, 
        HEALTH: 10,
        STRENGTH: 6,
        DEFENCE: 1,
        SPEED: 15,
        PERCEPTION: 5,
        MAXHEALTH: 10, 
        EXP: 75,
        DESCWORDS: ['small shark']},
    'Bruce' : {
        GROUNDDESC: 'The biggest shark you have ever seen, your entire house would fit into his enormous mouth, his teeth are about the size of you... times 3.',
        SHORTDESC: 'Biggest Shark of all time',
        LONGDESC: 'This fish is not just a shark, it is so incredibly big that you\'re unable to see his complete body, there have been fantasies of a shark bigger than any sea animal we have ever seen and you might just have stumbled upon it. Brucy the meg is ready to attack.',
        TALKABLE: True,
        GREETING: 'Bruce: Hii, the name is Bruce, why is a bite like you swmimming in these waters?',
        GOLD: 100,
        HEALTH: 80,
        STRENGTH: 80,
        DEFENCE: 50,
        SPEED: 10,
        PERCEPTION: 20,
        MAXHEALTH: 80,
        EXP: 600,
        DROPITEM: 'Shark Tooth',
        DESCWORDS: ['bruce', 'brucy', 'megalodon']},
    'Pufferfish' : {
        GROUNDDESC: 'Seemed to be quite little at first, but it blew up instantly to form a big round ball with spikes sticking out of it on every side, poisonous ofcourse',
        SHORTDESC: 'A Pufferfish',
        LONGDESC: 'An angry pufferfish who was already hostile and ready to attack before you even entered his path because he was having a bad day.',
        TALKABLE: True,
        GREETING: 'Pufferfish: Poof...',
        GOLD: 15,
        HEALTH: 15,
        STRENGTH: 30,
        DEFENCE: 10,
        SPEED: 10,
        PERCEPTION: 10,
        MAXHEALTH: 15,
        EXP: 100,
        DESCWORDS: ['pufferfish']},
    'Jellyfish' : {
        GROUNDDESC: 'Swimming around freely, nice as boneless as ever, until you came across it, a direct threat to its lane.',
        SHORTDESC: 'A Jellyfish',
        LONGDESC: 'Tentacles ready to sting, jelly ready to swim',
        TALKABLE: True,
        GREETING: 'Jellypudding... hmm',
        GOLD: 20,
        HEALTH: 20,
        STRENGTH: 25,
        DEFENCE: 15,
        SPEED: 25,
        PERCEPTION: 5,
        MAXHEALTH: 20,
        EXP: 100,
        DESCWORDS: ['Jellyfish']},
    'Octopus' : {
        GROUNDDESC: 'Tentacles ready to strangle you, teeth ready to eat you, this octopus doesn\'t get a free meal every day so it will do everything to try to kill you.',
        SHORTDESC: 'An Octopus',
        LONGDESC: 'Octopusses are able to kill sharks if they want to, this one wont hesitate for a second before attacking.',
        TALKABLE: True,
        GREETING: 'Octopus: My wife, Octopussy, will be delighted when I come home with your dead body this afternoon... shlurp',
        GOLD: 20,
        HEALTH: 30,
        STRENGTH: 30,
        DEFENCE: 20,
        SPEED: 25,
        PERCEPTION: 10,
        MAXHEALTH: 30,
        EXP: 125,
        DESCWORDS: ['Octopus']},
    'Sharktopus' : {
        GROUNDDESC: 'A weird combination of 2 dangerous animals who like to kill other fish, a sharkmouth with tenticles like an octopus.',
        SHORTDESC: 'A Sharktopus',
        LONGDESC: 'Mouth of a shark with tenticles of an octopus, fast, deadly, smart, deadly, strong and deadly...',
        TALKABLE: True,
        GREETING: 'Sharktopus: God left me unfinished, my mom was a Shark, my dad was an Octopus, I am not proud of what I am, I am proud however, of who I am, to be or not to be, that is truly the question',
        GOLD: 60,
        HEALTH: 50,
        STRENGTH: 85,
        DEFENCE: 30,
        SPEED: 20,
        PERCEPTION: 10,
        MAXHEALTH: 50,
        EXP: 400,
        DESCWORDS: ['sharktopus', 'weirdest creature ever', 'mofokking sharktopus', 'jerry the sharktopus']},
    'Scared Adventurer' : {
        GROUNDDESC: 'A haggard looking man is looking into the fire.',
        SHORTDESC: 'The adventurer',
        LONGDESC: 'His clothes are ripped and .',
        TALKABLE: True,
        GREETING: 'Hello, I am a real dummy.',
        GOLD: 5,
        HEALTH: 1,
        STRENGTH: 0,
        DEFENCE: 5,
        SPEED: 0,
        PERCEPTION: 0,
        MAXHEALTH: 1, 
        EXP: 15,
        DROPITEM: [],
        DESCWORDS: ['adventurer']},
    'Fire Spirit' : {
        LONGDESC: 'The fire spirits looks at you, you can feel a murderous aura',
        SHORTDESC: 'The Fire Spirit',
        GROUNDDESC: 'Spirits are beings which one should fear, combined with fire one should be afraid',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 2,
        HEALTH: 5,
        STRENGTH: 3,
        DEFENCE: 3,
        SPEED: 1,
        PERCEPTION: 1,
        MAXHEALTH: 5, 
        EXP: 5,
        DESCWORDS: ['spirit', 'fire spirit', 'Spirit', 'Fire Spirit']},
     'Large Fire Spirit' : {
        LONGDESC: 'The fire spirits looks at you, you can feel a murderous aura',
        SHORTDESC: 'The Large Fire Spirit',
        GROUNDDESC: 'Spirits are beings which one should fear, combined with fire one should be afraid, together with this size one should be terrified.',
        TALKABLE: True,
        GREETING: 'It patiently awaits your actions',
        GOLD: 5,
        HEALTH: 7,
        STRENGTH: 4,
        DEFENCE: 3,
        SPEED: 3,
        PERCEPTION: 5,
        MAXHEALTH: 7, 
        EXP: 7,
        DESCWORDS: ['spirit', 'fire spirit', 'Spirit', 'Fire Spirit', 'Large Fire Spirit', 'large fire spirit']},
    'Small Fire Spirit' : {
        GROUNDDESC: 'The fire spirits looks at you, you can feel a murderous aura',
        SHORTDESC: 'The Small Fire Spirit',
        LONGDESC: 'Spirits are beings which one should fear, combined with fire one should be afraid, together with this size one should be terrified.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 50,
        HEALTH: 3,
        STRENGTH: 3,
        DEFENCE: 1,
        SPEED: 7,
        PERCEPTION: 2,
        MAXHEALTH: 3, 
        EXP: 7,
        DESCWORDS: ['spirit', 'fire spirit', 'Spirit', 'Fire Spirit','Small Fire Spirit', 'small fire spirit']},
    'Cyronax, Spawn of Ash' : { 
        BOSS: True,
        LONGDESC: 'A golem blocks your path',
        SHORTDESC: 'The Fire Golem',
        GROUNDDESC: 'This Golem is nothing like you encountered before. It flames on it\'s body exclaim such heat that it makes the air arid. Contrary to the huge amount of power it exerts, it is small compared to the golems you have met before.', 
        TALKABLE: True,
        GREETING:'The Fire Golem awaits your actions patiently', 
        GOLD: 10,
        HEALTH: 15,
        STRENGTH: 7,
        DEFENCE: 2,
        SPEED: 3,
        PERCEPTION: 1, 
        MAXHEALTH: 15,
        EXP: 30, 
        DESCWORDS:['Fire Golem','Golem','Thing', 'fire golem', 'golem, Cyronax, cyronax']},
     'Earth Spirit' : {
        GROUNDDESC: 'The spirit gives you an eery feeling',
        SHORTDESC: 'The Earth Spirit',
        LONGDESC: 'It stare gives you the feeling as if you are being sucked into the earth itself.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 4,
        HEALTH: 6,
        STRENGTH: 3,
        DEFENCE: 3,
        SPEED: 2,
        PERCEPTION: 1,
        MAXHEALTH: 6, 
        EXP: 5,
        DESCWORDS: ['spirit', 'earth spirit', 'Spirit', 'Earth Spirit']},
     'Large Earth Spirit' : {
        GROUNDDESC: 'The spirit gives you an eery feeling',
        SHORTDESC: 'The Earth Spirit',
        LONGDESC: 'It stare gives you the feeling as if you are being crushed by the earth itself.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 5,
        HEALTH: 12,
        STRENGTH: 5,
        DEFENCE: 5,
        SPEED: 3,
        PERCEPTION: 2,
        MAXHEALTH: 12, 
        EXP: 9,
        DESCWORDS: ['spirit', 'earth spirit', 'Spirit', 'Earth Spirit', 'Large Earth Spirit','large earth spirit']},
     'Small Earth Spirit' : {
        GROUNDDESC: 'The spirit gives you an eery feeling',
        SHORTDESC: 'The Earth Spirit',
        LONGDESC: 'It stare gives you the feeling as if you are being trailed by the earth itself.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 5,
        HEALTH: 4,
        STRENGTH: 4,
        DEFENCE: 1,
        SPEED: 2,
        PERCEPTION: 2,
        MAXHEALTH: 4, 
        EXP: 10,
        DESCWORDS: ['spirit', 'earth spirit', 'Spirit', 'Earth Spirit', 'Small Earth Spirit','small earth spirit']},
    'Chelchis, Kell of Stone' : { 
        BOSS: True,
        GROUNDDESC: 'A golem blocks your path',
        SHORTDESC: 'The Fire Golem',
        LONGDESC: 'The Golems in this tower are something special. They differ from those you have seen. This golem is huge, it seems to be as tall as your home.', 
        TALKABLE: True,
        GREETING:'Chelchis awaits your actions patiently', 
        GOLD: 12,
        HEALTH: 18,
        STRENGTH: 8,
        DEFENCE: 2,
        SPEED: 1,
        PERCEPTION: 1, 
        MAXHEALTH: 18,
        EXP: 30,
        DESCWORDS: ['Golem','golem','Chelchis','chelchis']},
    'Water Spirit' : {
        GROUNDDESC: 'A body forms out of the water',
        SHORTDESC: 'The Water Spirit',
        LONGDESC: 'The water forms itself into a body. You wonder how to attack this.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 4,
        HEALTH: 7,
        STRENGTH: 4,
        DEFENCE: 4,
        SPEED: 5,
        PERCEPTION: 2,
        MAXHEALTH: 7, 
        EXP: 15,
        DESCWORDS: ['spirit', 'water spirit', 'Spirit', 'Water Spirit']},
     'Large Water Spirit' : {
        GROUNDDESC: 'A body forms out of the water',
        SHORTDESC: 'The Large Water Spirit',
        LONGDESC: 'The water forms itself into a body. You wonder how to attack this.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 5,
        HEALTH: 13,
        STRENGTH: 5,
        DEFENCE: 5,
        SPEED: 7,
        PERCEPTION: 4,
        MAXHEALTH: 13, 
        EXP: 9,
        DESCWORDS: ['spirit', 'water spirit', 'Spirit', 'Water Spirit', 'Large Water Spirit','large water spirit']},
     'Small Water Spirit' : {
        GROUNDDESC: 'A body forms out of the water',
        SHORTDESC: 'The Small Water Spirit',
        LONGDESC: 'The water forms itself into a body. You wonder how to attack this.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 5,
        HEALTH: 7,
        STRENGTH: 7,
        DEFENCE: 5,
        SPEED: 5,
        PERCEPTION: 5,
        MAXHEALTH: 5, 
        EXP: 15,
        DESCWORDS: ['spirit', 'water spirit', 'Spirit', 'Water Spirit', 'Small Water Spirit','small water spirit']},
    'Air Spirit' : {
        GROUNDDESC: 'The fog forms into spirits.', 
        SHORTDESC: 'The Air Spirit',
        LONGDESC: 'The mist forms itself into a body. You wonder how to attack this.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 5,
        HEALTH: 7,
        STRENGTH: 9,
        DEFENCE: 9,
        SPEED: 20,
        PERCEPTION: 15,
        MAXHEALTH: 75, 
        EXP: 8,
        DESCWORDS: ['spirit', 'air spirit', 'Spirit', 'Air Spirit']},
    'Large Air Spirit' : {
        GROUNDDESC: 'A body forms out of the mist',
        SHORTDESC: 'The Large Air Spirit',
        LONGDESC: 'The fog forms itself into a body. You wonder how to attack this.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 5,
        HEALTH: 15,
        STRENGTH: 9,
        DEFENCE: 6,
        SPEED: 12,
        PERCEPTION: 12,
        MAXHEALTH: 15, 
        EXP: 20,
        DESCWORDS: ['spirit', 'air spirit', 'Spirit', 'Air Spirit', 'Large Air Spirit','large air spirit']},
    'Small Air Spirit' : {
        GROUNDDESC: 'A body forms out of the fog',
        SHORTDESC: 'The Small Air Spirit',
        LONGDESC: 'The fog forms itself into a body. You wonder how to attack this.',
        TALKABLE: True,
        GREETING: 'It awaits your actions',
        GOLD: 5,
        HEALTH: 4,
        STRENGTH: 5,
        DEFENCE: 2,
        SPEED: 3,
        PERCEPTION: 10,
        MAXHEALTH: 4, 
        EXP: 8,
        DESCWORDS: ['spirit', 'air spirit', 'Spirit', 'Air Spirit', 'Small Air Spirit','small air spirit']},
   'Callisto Gan' : { 
        BOSS: True,
        GROUNDDESC: 'A golem blocks your path',
        SHORTDESC: 'The Water Golem',
        LONGDESC: 'At first you thought that golems were made out of stone, yet this golem appears to be made out of water. It seems weak, but you know that is not true.', 
        TALKABLE: True,
        GREETING:'Chelchis awaits your actions patiently', 
        GOLD: 15,
        HEALTH: 15,
        STRENGTH: 10,
        DEFENCE: 8,
        SPEED: 8,
        PERCEPTION: 15, 
        MAXHEALTH: 15,
        EXP: 35, 
        DESCWORDS: ['golem','Golem','Callisto','callisto']},
    'Rahn' : { 
        BOSS: True,
        GROUNDDESC: 'A golem blocks your path',
        SHORTDESC: 'The Air Golem',
        LONGDESC: 'This golem is, sadly, the size of the golems you have seen in the cave. A mixture between air and rocks hurls towards you.', 
        TALKABLE: False,
        GREETING:'',
        GOLD: 20,
        HEALTH: 10,
        STRENGTH: 10,
        DEFENCE: 8,
        SPEED: 2,
        PERCEPTION: 2, 
        MAXHEALTH: 15,
        EXP: 35, 
        DESCWORDS: ['golem','Golem','Rahn','rahn']},
    'Patty' : {
        GROUNDDESC: 'Old Patty',
        SHORTDESC: 'Patty',
        LONGDESC: 'An old fat lady that goes by the name of Patty, she owns a shop called Patty\'s Furniture in which she sells furniture and junk',
        TALKABLE: True,
        GREETING: 'Hewjo young mah! Wewcome ih my shop. I have heard of the wittle queste you\'ve been busy with. I must say; I find it ratheh pleasant, knowing to have a true hewo on our side! Take whatever you need love, to borrow of course. Buying price is not negotiable.',
        GOLD: 4,
        HEALTH: 10,
        STRENGTH: 2,
        DEFENCE: 5,
        SPEED: 2,
        PERCEPTION: 5,
        MAXHEALTH: 10,
        EXP: 20,
        DESCWORDS: ['patty', 'Patty', 'Old Patty']},
    'Wild Motman' : {
        GROUNDDESC: 'A Wild Motman has appeared! It\'s majestic, It\'s beautiful, this is most likely the prettiest creature you have ever seen.',
        SHORTDESC: 'Motman',
        LONGDESC: 'The motman... They say he has lived for several centuries. He comes straight from the country roads of east-virginia. His wings are so majestic',
        TALKABLE: True,
        GREETING: 'Hello, I am a real dummy.',
        GOLD: 5,
        HEALTH: 1,
        STRENGTH: 0,
        DEFENCE: 5,
        SPEED: 0,
        PERCEPTION: 0,
        MAXHEALTH: 1, 
        EXP: 15,
        SIDEQUEST: True,
        SIDEQUESTSTART: 'Can I haz Showd Swowd and Minow Health Potion plz uWu?',
        SIDEQUESTITEMS: ['Short Sword', 'Minor Health Potion'],
        SIDEQUESTEND: 'Thank u vewy, vewy much. *notices big swowd* Pwease take my big, heavy swowd :3!',
        SIDEQUESTREWARD: ['Dragonslayer Sword'],
        SIDEQUESTINV: [],
        DROPITEM: [],
        DESCWORDS: ['motman']},
     'Mutated Rat' : {
        GROUNDDESC: 'You knew that rats lurked in the sewers, but this is... something one would never expect.',
        SHORTDESC: 'Mutated Rat',
        LONGDESC: 'It\'s some kind of manrat. Something straight out of a horror story.',
        TALKABLE: True,
        GREETING: 'GoT AnY SnAcKs??',
        GOLD: 50,
        HEALTH: 40,
        STRENGTH: 50,
        DEFENCE: 10,
        SPEED: 15,
        PERCEPTION: 2,
        MAXHEALTH: 40, 
        EXP: 120,
        DESCWORDS: ['rat']},
    'Statue' : {
        BOSS: True,
        GROUNDDESC: 'A large walking statue appears before you.',
        SHORTDESC: 'Statue',
        LONGDESC: 'It seems that the sewers',
        TALKABLE: True,
        GREETING: '. . .',
        GOLD: 50,
        HEALTH: 40,
        STRENGTH: 50,
        DEFENCE: 10,
        SPEED: 15,
        PERCEPTION: 2,
        MAXHEALTH: 40, 
        EXP: 120,
        DESCWORDS: ['Statue']},



        
    }